// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/taskboard.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskBoard_AddTask_FullMethodName         = "/nanocursor.taskboard.TaskBoard/AddTask"
	TaskBoard_UpdateTask_FullMethodName      = "/nanocursor.taskboard.TaskBoard/UpdateTask"
	TaskBoard_RemoveTask_FullMethodName      = "/nanocursor.taskboard.TaskBoard/RemoveTask"
	TaskBoard_GetTask_FullMethodName         = "/nanocursor.taskboard.TaskBoard/GetTask"
	TaskBoard_ListTasks_FullMethodName       = "/nanocursor.taskboard.TaskBoard/ListTasks"
	TaskBoard_ApplyTaskStatus_FullMethodName = "/nanocursor.taskboard.TaskBoard/ApplyTaskStatus"
	TaskBoard_GetReadyNodes_FullMethodName   = "/nanocursor.taskboard.TaskBoard/GetReadyNodes"
	TaskBoard_ConnectTasks_FullMethodName    = "/nanocursor.taskboard.TaskBoard/ConnectTasks"
	TaskBoard_DisconnectTasks_FullMethodName = "/nanocursor.taskboard.TaskBoard/DisconnectTasks"
	TaskBoard_SaveBoard_FullMethodName       = "/nanocursor.taskboard.TaskBoard/SaveBoard"
	TaskBoard_LoadBoard_FullMethodName       = "/nanocursor.taskboard.TaskBoard/LoadBoard"
	TaskBoard_BuildBoard_FullMethodName      = "/nanocursor.taskboard.TaskBoard/BuildBoard"
	TaskBoard_GetBoardState_FullMethodName   = "/nanocursor.taskboard.TaskBoard/GetBoardState"
	TaskBoard_Health_FullMethodName          = "/nanocursor.taskboard.TaskBoard/Health"
)

// TaskBoardClient is the client API for TaskBoard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskBoardClient interface {
	AddTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*AddTaskResponse, error)
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error)
	RemoveTask(ctx context.Context, in *RemoveTaskRequest, opts ...grpc.CallOption) (*RemoveTaskResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	ApplyTaskStatus(ctx context.Context, in *ApplyTaskStatusRequest, opts ...grpc.CallOption) (*ApplyTaskStatusResponse, error)
	GetReadyNodes(ctx context.Context, in *GetReadyNodesRequest, opts ...grpc.CallOption) (*GetReadyNodesResponse, error)
	ConnectTasks(ctx context.Context, in *ConnectTasksRequest, opts ...grpc.CallOption) (*ConnectTasksResponse, error)
	DisconnectTasks(ctx context.Context, in *DisconnectTasksRequest, opts ...grpc.CallOption) (*DisconnectTasksResponse, error)
	SaveBoard(ctx context.Context, in *SaveBoardRequest, opts ...grpc.CallOption) (*SaveBoardResponse, error)
	LoadBoard(ctx context.Context, in *LoadBoardRequest, opts ...grpc.CallOption) (*LoadBoardResponse, error)
	BuildBoard(ctx context.Context, in *BuildBoardRequest, opts ...grpc.CallOption) (*BuildBoardResponse, error)
	GetBoardState(ctx context.Context, in *GetBoardStateRequest, opts ...grpc.CallOption) (*GetBoardStateResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type taskBoardClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskBoardClient(cc grpc.ClientConnInterface) TaskBoardClient {
	return &taskBoardClient{cc}
}

func (c *taskBoardClient) AddTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*AddTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTaskResponse)
	err := c.cc.Invoke(ctx, TaskBoard_AddTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTaskResponse)
	err := c.cc.Invoke(ctx, TaskBoard_UpdateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardClient) RemoveTask(ctx context.Context, in *RemoveTaskRequest, opts ...grpc.CallOption) (*RemoveTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTaskResponse)
	err := c.cc.Invoke(ctx, TaskBoard_RemoveTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, TaskBoard_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, TaskBoard_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardClient) ApplyTaskStatus(ctx context.Context, in *ApplyTaskStatusRequest, opts ...grpc.CallOption) (*ApplyTaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyTaskStatusResponse)
	err := c.cc.Invoke(ctx, TaskBoard_ApplyTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardClient) GetReadyNodes(ctx context.Context, in *GetReadyNodesRequest, opts ...grpc.CallOption) (*GetReadyNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReadyNodesResponse)
	err := c.cc.Invoke(ctx, TaskBoard_GetReadyNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardClient) ConnectTasks(ctx context.Context, in *ConnectTasksRequest, opts ...grpc.CallOption) (*ConnectTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectTasksResponse)
	err := c.cc.Invoke(ctx, TaskBoard_ConnectTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardClient) DisconnectTasks(ctx context.Context, in *DisconnectTasksRequest, opts ...grpc.CallOption) (*DisconnectTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectTasksResponse)
	err := c.cc.Invoke(ctx, TaskBoard_DisconnectTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardClient) SaveBoard(ctx context.Context, in *SaveBoardRequest, opts ...grpc.CallOption) (*SaveBoardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveBoardResponse)
	err := c.cc.Invoke(ctx, TaskBoard_SaveBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardClient) LoadBoard(ctx context.Context, in *LoadBoardRequest, opts ...grpc.CallOption) (*LoadBoardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadBoardResponse)
	err := c.cc.Invoke(ctx, TaskBoard_LoadBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardClient) BuildBoard(ctx context.Context, in *BuildBoardRequest, opts ...grpc.CallOption) (*BuildBoardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildBoardResponse)
	err := c.cc.Invoke(ctx, TaskBoard_BuildBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardClient) GetBoardState(ctx context.Context, in *GetBoardStateRequest, opts ...grpc.CallOption) (*GetBoardStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBoardStateResponse)
	err := c.cc.Invoke(ctx, TaskBoard_GetBoardState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, TaskBoard_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskBoardServer is the server API for TaskBoard service.
// All implementations must embed UnimplementedTaskBoardServer
// for forward compatibility.
type TaskBoardServer interface {
	AddTask(context.Context, *AddTaskRequest) (*AddTaskResponse, error)
	UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error)
	RemoveTask(context.Context, *RemoveTaskRequest) (*RemoveTaskResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	ApplyTaskStatus(context.Context, *ApplyTaskStatusRequest) (*ApplyTaskStatusResponse, error)
	GetReadyNodes(context.Context, *GetReadyNodesRequest) (*GetReadyNodesResponse, error)
	ConnectTasks(context.Context, *ConnectTasksRequest) (*ConnectTasksResponse, error)
	DisconnectTasks(context.Context, *DisconnectTasksRequest) (*DisconnectTasksResponse, error)
	SaveBoard(context.Context, *SaveBoardRequest) (*SaveBoardResponse, error)
	LoadBoard(context.Context, *LoadBoardRequest) (*LoadBoardResponse, error)
	BuildBoard(context.Context, *BuildBoardRequest) (*BuildBoardResponse, error)
	GetBoardState(context.Context, *GetBoardStateRequest) (*GetBoardStateResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedTaskBoardServer()
}

// UnimplementedTaskBoardServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskBoardServer struct{}

func (UnimplementedTaskBoardServer) AddTask(context.Context, *AddTaskRequest) (*AddTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTask not implemented")
}
func (UnimplementedTaskBoardServer) UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedTaskBoardServer) RemoveTask(context.Context, *RemoveTaskRequest) (*RemoveTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTask not implemented")
}
func (UnimplementedTaskBoardServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTaskBoardServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedTaskBoardServer) ApplyTaskStatus(context.Context, *ApplyTaskStatusRequest) (*ApplyTaskStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyTaskStatus not implemented")
}
func (UnimplementedTaskBoardServer) GetReadyNodes(context.Context, *GetReadyNodesRequest) (*GetReadyNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReadyNodes not implemented")
}
func (UnimplementedTaskBoardServer) ConnectTasks(context.Context, *ConnectTasksRequest) (*ConnectTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectTasks not implemented")
}
func (UnimplementedTaskBoardServer) DisconnectTasks(context.Context, *DisconnectTasksRequest) (*DisconnectTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectTasks not implemented")
}
func (UnimplementedTaskBoardServer) SaveBoard(context.Context, *SaveBoardRequest) (*SaveBoardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveBoard not implemented")
}
func (UnimplementedTaskBoardServer) LoadBoard(context.Context, *LoadBoardRequest) (*LoadBoardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadBoard not implemented")
}
func (UnimplementedTaskBoardServer) BuildBoard(context.Context, *BuildBoardRequest) (*BuildBoardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildBoard not implemented")
}
func (UnimplementedTaskBoardServer) GetBoardState(context.Context, *GetBoardStateRequest) (*GetBoardStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBoardState not implemented")
}
func (UnimplementedTaskBoardServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedTaskBoardServer) mustEmbedUnimplementedTaskBoardServer() {}
func (UnimplementedTaskBoardServer) testEmbeddedByValue()                   {}

// UnsafeTaskBoardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskBoardServer will
// result in compilation errors.
type UnsafeTaskBoardServer interface {
	mustEmbedUnimplementedTaskBoardServer()
}

func RegisterTaskBoardServer(s grpc.ServiceRegistrar, srv TaskBoardServer) {
	// If the following call panics, it indicates UnimplementedTaskBoardServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskBoard_ServiceDesc, srv)
}

func _TaskBoard_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoard_AddTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServer).AddTask(ctx, req.(*AddTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoard_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoard_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoard_RemoveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServer).RemoveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoard_RemoveTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServer).RemoveTask(ctx, req.(*RemoveTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoard_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoard_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoard_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoard_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoard_ApplyTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyTaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServer).ApplyTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoard_ApplyTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServer).ApplyTaskStatus(ctx, req.(*ApplyTaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoard_GetReadyNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadyNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServer).GetReadyNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoard_GetReadyNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServer).GetReadyNodes(ctx, req.(*GetReadyNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoard_ConnectTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServer).ConnectTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoard_ConnectTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServer).ConnectTasks(ctx, req.(*ConnectTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoard_DisconnectTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServer).DisconnectTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoard_DisconnectTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServer).DisconnectTasks(ctx, req.(*DisconnectTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoard_SaveBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServer).SaveBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoard_SaveBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServer).SaveBoard(ctx, req.(*SaveBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoard_LoadBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServer).LoadBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoard_LoadBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServer).LoadBoard(ctx, req.(*LoadBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoard_BuildBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServer).BuildBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoard_BuildBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServer).BuildBoard(ctx, req.(*BuildBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoard_GetBoardState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBoardStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServer).GetBoardState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoard_GetBoardState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServer).GetBoardState(ctx, req.(*GetBoardStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoard_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoard_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskBoard_ServiceDesc is the grpc.ServiceDesc for TaskBoard service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskBoard_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanocursor.taskboard.TaskBoard",
	HandlerType: (*TaskBoardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTask",
			Handler:    _TaskBoard_AddTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _TaskBoard_UpdateTask_Handler,
		},
		{
			MethodName: "RemoveTask",
			Handler:    _TaskBoard_RemoveTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TaskBoard_GetTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _TaskBoard_ListTasks_Handler,
		},
		{
			MethodName: "ApplyTaskStatus",
			Handler:    _TaskBoard_ApplyTaskStatus_Handler,
		},
		{
			MethodName: "GetReadyNodes",
			Handler:    _TaskBoard_GetReadyNodes_Handler,
		},
		{
			MethodName: "ConnectTasks",
			Handler:    _TaskBoard_ConnectTasks_Handler,
		},
		{
			MethodName: "DisconnectTasks",
			Handler:    _TaskBoard_DisconnectTasks_Handler,
		},
		{
			MethodName: "SaveBoard",
			Handler:    _TaskBoard_SaveBoard_Handler,
		},
		{
			MethodName: "LoadBoard",
			Handler:    _TaskBoard_LoadBoard_Handler,
		},
		{
			MethodName: "BuildBoard",
			Handler:    _TaskBoard_BuildBoard_Handler,
		},
		{
			MethodName: "GetBoardState",
			Handler:    _TaskBoard_GetBoardState_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _TaskBoard_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/taskboard.proto",
}
