# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.mcp.proto import mcp_pb2 as mcp__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mcp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MCPServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListPresets = channel.unary_unary(
                '/nanocursor.mcp.MCPService/ListPresets',
                request_serializer=mcp__pb2.ListPresetsRequest.SerializeToString,
                response_deserializer=mcp__pb2.PresetList.FromString,
                _registered_method=True)
        self.ListServers = channel.unary_unary(
                '/nanocursor.mcp.MCPService/ListServers',
                request_serializer=mcp__pb2.ListServersRequest.SerializeToString,
                response_deserializer=mcp__pb2.ServerList.FromString,
                _registered_method=True)
        self.ProbeServer = channel.unary_unary(
                '/nanocursor.mcp.MCPService/ProbeServer',
                request_serializer=mcp__pb2.ProbeRequest.SerializeToString,
                response_deserializer=mcp__pb2.ProbeResult.FromString,
                _registered_method=True)
        self.ListServerTools = channel.unary_unary(
                '/nanocursor.mcp.MCPService/ListServerTools',
                request_serializer=mcp__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=mcp__pb2.ToolList.FromString,
                _registered_method=True)
        self.CallTool = channel.unary_unary(
                '/nanocursor.mcp.MCPService/CallTool',
                request_serializer=mcp__pb2.CallToolRequest.SerializeToString,
                response_deserializer=mcp__pb2.CallResult.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/nanocursor.mcp.MCPService/Health',
                request_serializer=mcp__pb2.HealthRequest.SerializeToString,
                response_deserializer=mcp__pb2.HealthResponse.FromString,
                _registered_method=True)


class MCPServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListPresets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProbeServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServerTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MCPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListPresets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPresets,
                    request_deserializer=mcp__pb2.ListPresetsRequest.FromString,
                    response_serializer=mcp__pb2.PresetList.SerializeToString,
            ),
            'ListServers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServers,
                    request_deserializer=mcp__pb2.ListServersRequest.FromString,
                    response_serializer=mcp__pb2.ServerList.SerializeToString,
            ),
            'ProbeServer': grpc.unary_unary_rpc_method_handler(
                    servicer.ProbeServer,
                    request_deserializer=mcp__pb2.ProbeRequest.FromString,
                    response_serializer=mcp__pb2.ProbeResult.SerializeToString,
            ),
            'ListServerTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServerTools,
                    request_deserializer=mcp__pb2.ListToolsRequest.FromString,
                    response_serializer=mcp__pb2.ToolList.SerializeToString,
            ),
            'CallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=mcp__pb2.CallToolRequest.FromString,
                    response_serializer=mcp__pb2.CallResult.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=mcp__pb2.HealthRequest.FromString,
                    response_serializer=mcp__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nanocursor.mcp.MCPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nanocursor.mcp.MCPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MCPService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListPresets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.mcp.MCPService/ListPresets',
            mcp__pb2.ListPresetsRequest.SerializeToString,
            mcp__pb2.PresetList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.mcp.MCPService/ListServers',
            mcp__pb2.ListServersRequest.SerializeToString,
            mcp__pb2.ServerList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProbeServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.mcp.MCPService/ProbeServer',
            mcp__pb2.ProbeRequest.SerializeToString,
            mcp__pb2.ProbeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServerTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.mcp.MCPService/ListServerTools',
            mcp__pb2.ListToolsRequest.SerializeToString,
            mcp__pb2.ToolList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.mcp.MCPService/CallTool',
            mcp__pb2.CallToolRequest.SerializeToString,
            mcp__pb2.CallResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.mcp.MCPService/Health',
            mcp__pb2.HealthRequest.SerializeToString,
            mcp__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
