// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/executor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreviewRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Command          string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Cwd              string                 `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	WorkspaceDir     string                 `protobuf:"bytes,3,opt,name=workspace_dir,json=workspaceDir,proto3" json:"workspace_dir,omitempty"`
	PermissionLevel  string                 `protobuf:"bytes,4,opt,name=permission_level,json=permissionLevel,proto3" json:"permission_level,omitempty"`
	RequiresApproval bool                   `protobuf:"varint,5,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	ApprovalId       string                 `protobuf:"bytes,6,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	ApprovalToken    string                 `protobuf:"bytes,7,opt,name=approval_token,json=approvalToken,proto3" json:"approval_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PreviewRequest) Reset() {
	*x = PreviewRequest{}
	mi := &file_proto_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRequest) ProtoMessage() {}

func (x *PreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRequest.ProtoReflect.Descriptor instead.
func (*PreviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{0}
}

func (x *PreviewRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *PreviewRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *PreviewRequest) GetWorkspaceDir() string {
	if x != nil {
		return x.WorkspaceDir
	}
	return ""
}

func (x *PreviewRequest) GetPermissionLevel() string {
	if x != nil {
		return x.PermissionLevel
	}
	return ""
}

func (x *PreviewRequest) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

func (x *PreviewRequest) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *PreviewRequest) GetApprovalToken() string {
	if x != nil {
		return x.ApprovalToken
	}
	return ""
}

type Decision struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Allowed          bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	PermissionLevel  string                 `protobuf:"bytes,2,opt,name=permission_level,json=permissionLevel,proto3" json:"permission_level,omitempty"`
	RequiresApproval bool                   `protobuf:"varint,3,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	ErrorCode        string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message          string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Reasons          []string               `protobuf:"bytes,6,rep,name=reasons,proto3" json:"reasons,omitempty"`
	WorkspaceDir     string                 `protobuf:"bytes,7,opt,name=workspace_dir,json=workspaceDir,proto3" json:"workspace_dir,omitempty"`
	Cwd              string                 `protobuf:"bytes,8,opt,name=cwd,proto3" json:"cwd,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_proto_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{1}
}

func (x *Decision) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *Decision) GetPermissionLevel() string {
	if x != nil {
		return x.PermissionLevel
	}
	return ""
}

func (x *Decision) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

func (x *Decision) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Decision) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Decision) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

func (x *Decision) GetWorkspaceDir() string {
	if x != nil {
		return x.WorkspaceDir
	}
	return ""
}

func (x *Decision) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

type ExecuteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Command          string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Cwd              string                 `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	WorkspaceDir     string                 `protobuf:"bytes,3,opt,name=workspace_dir,json=workspaceDir,proto3" json:"workspace_dir,omitempty"`
	TimeoutMs        int32                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	RunId            string                 `protobuf:"bytes,5,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ApprovalToken    string                 `protobuf:"bytes,6,opt,name=approval_token,json=approvalToken,proto3" json:"approval_token,omitempty"`
	PermissionLevel  string                 `protobuf:"bytes,7,opt,name=permission_level,json=permissionLevel,proto3" json:"permission_level,omitempty"`
	RequiresApproval bool                   `protobuf:"varint,8,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	ApprovalId       string                 `protobuf:"bytes,9,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	MaxStdoutChars   int32                  `protobuf:"varint,10,opt,name=max_stdout_chars,json=maxStdoutChars,proto3" json:"max_stdout_chars,omitempty"`
	MaxStderrChars   int32                  `protobuf:"varint,11,opt,name=max_stderr_chars,json=maxStderrChars,proto3" json:"max_stderr_chars,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecuteRequest) GetWorkspaceDir() string {
	if x != nil {
		return x.WorkspaceDir
	}
	return ""
}

func (x *ExecuteRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ExecuteRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecuteRequest) GetApprovalToken() string {
	if x != nil {
		return x.ApprovalToken
	}
	return ""
}

func (x *ExecuteRequest) GetPermissionLevel() string {
	if x != nil {
		return x.PermissionLevel
	}
	return ""
}

func (x *ExecuteRequest) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

func (x *ExecuteRequest) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *ExecuteRequest) GetMaxStdoutChars() int32 {
	if x != nil {
		return x.MaxStdoutChars
	}
	return 0
}

func (x *ExecuteRequest) GetMaxStderrChars() int32 {
	if x != nil {
		return x.MaxStderrChars
	}
	return 0
}

type ToolRun struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Command         string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Cwd             string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	ExitCode        int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout          string                 `protobuf:"bytes,6,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr          string                 `protobuf:"bytes,7,opt,name=stderr,proto3" json:"stderr,omitempty"`
	DurationMs      int64                  `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	TimedOut        bool                   `protobuf:"varint,9,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	ErrorCode       string                 `protobuf:"bytes,10,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message         string                 `protobuf:"bytes,11,opt,name=message,proto3" json:"message,omitempty"`
	StdoutTruncated bool                   `protobuf:"varint,12,opt,name=stdout_truncated,json=stdoutTruncated,proto3" json:"stdout_truncated,omitempty"`
	StderrTruncated bool                   `protobuf:"varint,13,opt,name=stderr_truncated,json=stderrTruncated,proto3" json:"stderr_truncated,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolRun) Reset() {
	*x = ToolRun{}
	mi := &file_proto_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRun) ProtoMessage() {}

func (x *ToolRun) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRun.ProtoReflect.Descriptor instead.
func (*ToolRun) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{3}
}

func (x *ToolRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolRun) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ToolRun) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ToolRun) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ToolRun) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ToolRun) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ToolRun) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ToolRun) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ToolRun) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *ToolRun) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ToolRun) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ToolRun) GetStdoutTruncated() bool {
	if x != nil {
		return x.StdoutTruncated
	}
	return false
}

func (x *ToolRun) GetStderrTruncated() bool {
	if x != nil {
		return x.StderrTruncated
	}
	return false
}

type GetToolRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToolRunRequest) Reset() {
	*x = GetToolRunRequest{}
	mi := &file_proto_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToolRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolRunRequest) ProtoMessage() {}

func (x *GetToolRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolRunRequest.ProtoReflect.Descriptor instead.
func (*GetToolRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{4}
}

func (x *GetToolRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AfterCursor   int32                  `protobuf:"varint,2,opt,name=after_cursor,json=afterCursor,proto3" json:"after_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_proto_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{5}
}

func (x *StreamEventsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StreamEventsRequest) GetAfterCursor() int32 {
	if x != nil {
		return x.AfterCursor
	}
	return 0
}

type ToolEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int32                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RunId         string                 `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Data          string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolEvent) Reset() {
	*x = ToolEvent{}
	mi := &file_proto_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolEvent) ProtoMessage() {}

func (x *ToolEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolEvent.ProtoReflect.Descriptor instead.
func (*ToolEvent) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{6}
}

func (x *ToolEvent) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ToolEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ToolEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ToolEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_proto_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{7}
}

func (x *CancelRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type CancelResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResult) Reset() {
	*x = CancelResult{}
	mi := &file_proto_executor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResult) ProtoMessage() {}

func (x *CancelResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResult.ProtoReflect.Descriptor instead.
func (*CancelResult) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{8}
}

func (x *CancelResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_executor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{9}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_executor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_executor_proto protoreflect.FileDescriptor

const file_proto_executor_proto_rawDesc = "" +
	"\n" +
	"\x14proto/executor.proto\x12\x13nanocursor.executor\"\x81\x02\n" +
	"\x0ePreviewRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x12#\n" +
	"\rworkspace_dir\x18\x03 \x01(\tR\fworkspaceDir\x12)\n" +
	"\x10permission_level\x18\x04 \x01(\tR\x0fpermissionLevel\x12+\n" +
	"\x11requires_approval\x18\x05 \x01(\bR\x10requiresApproval\x12\x1f\n" +
	"\vapproval_id\x18\x06 \x01(\tR\n" +
	"approvalId\x12%\n" +
	"\x0eapproval_token\x18\a \x01(\tR\rapprovalToken\"\x86\x02\n" +
	"\bDecision\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12)\n" +
	"\x10permission_level\x18\x02 \x01(\tR\x0fpermissionLevel\x12+\n" +
	"\x11requires_approval\x18\x03 \x01(\bR\x10requiresApproval\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x18\n" +
	"\areasons\x18\x06 \x03(\tR\areasons\x12#\n" +
	"\rworkspace_dir\x18\a \x01(\tR\fworkspaceDir\x12\x10\n" +
	"\x03cwd\x18\b \x01(\tR\x03cwd\"\x8b\x03\n" +
	"\x0eExecuteRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x12#\n" +
	"\rworkspace_dir\x18\x03 \x01(\tR\fworkspaceDir\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\x12\x15\n" +
	"\x06run_id\x18\x05 \x01(\tR\x05runId\x12%\n" +
	"\x0eapproval_token\x18\x06 \x01(\tR\rapprovalToken\x12)\n" +
	"\x10permission_level\x18\a \x01(\tR\x0fpermissionLevel\x12+\n" +
	"\x11requires_approval\x18\b \x01(\bR\x10requiresApproval\x12\x1f\n" +
	"\vapproval_id\x18\t \x01(\tR\n" +
	"approvalId\x12(\n" +
	"\x10max_stdout_chars\x18\n" +
	" \x01(\x05R\x0emaxStdoutChars\x12(\n" +
	"\x10max_stderr_chars\x18\v \x01(\x05R\x0emaxStderrChars\"\xf7\x02\n" +
	"\aToolRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x06 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\a \x01(\tR\x06stderr\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x03R\n" +
	"durationMs\x12\x1b\n" +
	"\ttimed_out\x18\t \x01(\bR\btimedOut\x12\x1d\n" +
	"\n" +
	"error_code\x18\n" +
	" \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\v \x01(\tR\amessage\x12)\n" +
	"\x10stdout_truncated\x18\f \x01(\bR\x0fstdoutTruncated\x12)\n" +
	"\x10stderr_truncated\x18\r \x01(\bR\x0fstderrTruncated\"#\n" +
	"\x11GetToolRunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x13StreamEventsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12!\n" +
	"\fafter_cursor\x18\x02 \x01(\x05R\vafterCursor\"z\n" +
	"\tToolEvent\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x05R\x03seq\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\"&\n" +
	"\rCancelRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"B\n" +
	"\fCancelResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rHealthRequest\"T\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion2\x98\x04\n" +
	"\x0fExecutorService\x12Q\n" +
	"\vPreviewTool\x12#.nanocursor.executor.PreviewRequest\x1a\x1d.nanocursor.executor.Decision\x12P\n" +
	"\vExecuteTool\x12#.nanocursor.executor.ExecuteRequest\x1a\x1c.nanocursor.executor.ToolRun\x12R\n" +
	"\n" +
	"GetToolRun\x12&.nanocursor.executor.GetToolRunRequest\x1a\x1c.nanocursor.executor.ToolRun\x12a\n" +
	"\x13StreamToolRunEvents\x12(.nanocursor.executor.StreamEventsRequest\x1a\x1e.nanocursor.executor.ToolEvent0\x01\x12V\n" +
	"\rCancelToolRun\x12\".nanocursor.executor.CancelRequest\x1a!.nanocursor.executor.CancelResult\x12Q\n" +
	"\x06Health\x12\".nanocursor.executor.HealthRequest\x1a#.nanocursor.executor.HealthResponseB'Z%nanocursor/go-services/executor/protob\x06proto3"

var (
	file_proto_executor_proto_rawDescOnce sync.Once
	file_proto_executor_proto_rawDescData []byte
)

func file_proto_executor_proto_rawDescGZIP() []byte {
	file_proto_executor_proto_rawDescOnce.Do(func() {
		file_proto_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_executor_proto_rawDesc), len(file_proto_executor_proto_rawDesc)))
	})
	return file_proto_executor_proto_rawDescData
}

var file_proto_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_executor_proto_goTypes = []any{
	(*PreviewRequest)(nil),      // 0: nanocursor.executor.PreviewRequest
	(*Decision)(nil),            // 1: nanocursor.executor.Decision
	(*ExecuteRequest)(nil),      // 2: nanocursor.executor.ExecuteRequest
	(*ToolRun)(nil),             // 3: nanocursor.executor.ToolRun
	(*GetToolRunRequest)(nil),   // 4: nanocursor.executor.GetToolRunRequest
	(*StreamEventsRequest)(nil), // 5: nanocursor.executor.StreamEventsRequest
	(*ToolEvent)(nil),           // 6: nanocursor.executor.ToolEvent
	(*CancelRequest)(nil),       // 7: nanocursor.executor.CancelRequest
	(*CancelResult)(nil),        // 8: nanocursor.executor.CancelResult
	(*HealthRequest)(nil),       // 9: nanocursor.executor.HealthRequest
	(*HealthResponse)(nil),      // 10: nanocursor.executor.HealthResponse
}
var file_proto_executor_proto_depIdxs = []int32{
	0,  // 0: nanocursor.executor.ExecutorService.PreviewTool:input_type -> nanocursor.executor.PreviewRequest
	2,  // 1: nanocursor.executor.ExecutorService.ExecuteTool:input_type -> nanocursor.executor.ExecuteRequest
	4,  // 2: nanocursor.executor.ExecutorService.GetToolRun:input_type -> nanocursor.executor.GetToolRunRequest
	5,  // 3: nanocursor.executor.ExecutorService.StreamToolRunEvents:input_type -> nanocursor.executor.StreamEventsRequest
	7,  // 4: nanocursor.executor.ExecutorService.CancelToolRun:input_type -> nanocursor.executor.CancelRequest
	9,  // 5: nanocursor.executor.ExecutorService.Health:input_type -> nanocursor.executor.HealthRequest
	1,  // 6: nanocursor.executor.ExecutorService.PreviewTool:output_type -> nanocursor.executor.Decision
	3,  // 7: nanocursor.executor.ExecutorService.ExecuteTool:output_type -> nanocursor.executor.ToolRun
	3,  // 8: nanocursor.executor.ExecutorService.GetToolRun:output_type -> nanocursor.executor.ToolRun
	6,  // 9: nanocursor.executor.ExecutorService.StreamToolRunEvents:output_type -> nanocursor.executor.ToolEvent
	8,  // 10: nanocursor.executor.ExecutorService.CancelToolRun:output_type -> nanocursor.executor.CancelResult
	10, // 11: nanocursor.executor.ExecutorService.Health:output_type -> nanocursor.executor.HealthResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_executor_proto_init() }
func file_proto_executor_proto_init() {
	if File_proto_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_executor_proto_rawDesc), len(file_proto_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_executor_proto_goTypes,
		DependencyIndexes: file_proto_executor_proto_depIdxs,
		MessageInfos:      file_proto_executor_proto_msgTypes,
	}.Build()
	File_proto_executor_proto = out.File
	file_proto_executor_proto_goTypes = nil
	file_proto_executor_proto_depIdxs = nil
}
