// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/executor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecutorService_PreviewTool_FullMethodName         = "/nanocursor.executor.ExecutorService/PreviewTool"
	ExecutorService_ExecuteTool_FullMethodName         = "/nanocursor.executor.ExecutorService/ExecuteTool"
	ExecutorService_GetToolRun_FullMethodName          = "/nanocursor.executor.ExecutorService/GetToolRun"
	ExecutorService_StreamToolRunEvents_FullMethodName = "/nanocursor.executor.ExecutorService/StreamToolRunEvents"
	ExecutorService_CancelToolRun_FullMethodName       = "/nanocursor.executor.ExecutorService/CancelToolRun"
	ExecutorService_Health_FullMethodName              = "/nanocursor.executor.ExecutorService/Health"
)

// ExecutorServiceClient is the client API for ExecutorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecutorServiceClient interface {
	PreviewTool(ctx context.Context, in *PreviewRequest, opts ...grpc.CallOption) (*Decision, error)
	ExecuteTool(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ToolRun, error)
	GetToolRun(ctx context.Context, in *GetToolRunRequest, opts ...grpc.CallOption) (*ToolRun, error)
	StreamToolRunEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ToolEvent], error)
	CancelToolRun(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResult, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type executorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutorServiceClient(cc grpc.ClientConnInterface) ExecutorServiceClient {
	return &executorServiceClient{cc}
}

func (c *executorServiceClient) PreviewTool(ctx context.Context, in *PreviewRequest, opts ...grpc.CallOption) (*Decision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Decision)
	err := c.cc.Invoke(ctx, ExecutorService_PreviewTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) ExecuteTool(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ToolRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolRun)
	err := c.cc.Invoke(ctx, ExecutorService_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) GetToolRun(ctx context.Context, in *GetToolRunRequest, opts ...grpc.CallOption) (*ToolRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolRun)
	err := c.cc.Invoke(ctx, ExecutorService_GetToolRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) StreamToolRunEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ToolEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExecutorService_ServiceDesc.Streams[0], ExecutorService_StreamToolRunEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, ToolEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutorService_StreamToolRunEventsClient = grpc.ServerStreamingClient[ToolEvent]

func (c *executorServiceClient) CancelToolRun(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResult)
	err := c.cc.Invoke(ctx, ExecutorService_CancelToolRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ExecutorService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutorServiceServer is the server API for ExecutorService service.
// All implementations must embed UnimplementedExecutorServiceServer
// for forward compatibility.
type ExecutorServiceServer interface {
	PreviewTool(context.Context, *PreviewRequest) (*Decision, error)
	ExecuteTool(context.Context, *ExecuteRequest) (*ToolRun, error)
	GetToolRun(context.Context, *GetToolRunRequest) (*ToolRun, error)
	StreamToolRunEvents(*StreamEventsRequest, grpc.ServerStreamingServer[ToolEvent]) error
	CancelToolRun(context.Context, *CancelRequest) (*CancelResult, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedExecutorServiceServer()
}

// UnimplementedExecutorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutorServiceServer struct{}

func (UnimplementedExecutorServiceServer) PreviewTool(context.Context, *PreviewRequest) (*Decision, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewTool not implemented")
}
func (UnimplementedExecutorServiceServer) ExecuteTool(context.Context, *ExecuteRequest) (*ToolRun, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedExecutorServiceServer) GetToolRun(context.Context, *GetToolRunRequest) (*ToolRun, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToolRun not implemented")
}
func (UnimplementedExecutorServiceServer) StreamToolRunEvents(*StreamEventsRequest, grpc.ServerStreamingServer[ToolEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamToolRunEvents not implemented")
}
func (UnimplementedExecutorServiceServer) CancelToolRun(context.Context, *CancelRequest) (*CancelResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelToolRun not implemented")
}
func (UnimplementedExecutorServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedExecutorServiceServer) mustEmbedUnimplementedExecutorServiceServer() {}
func (UnimplementedExecutorServiceServer) testEmbeddedByValue()                         {}

// UnsafeExecutorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutorServiceServer will
// result in compilation errors.
type UnsafeExecutorServiceServer interface {
	mustEmbedUnimplementedExecutorServiceServer()
}

func RegisterExecutorServiceServer(s grpc.ServiceRegistrar, srv ExecutorServiceServer) {
	// If the following call panics, it indicates UnimplementedExecutorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutorService_ServiceDesc, srv)
}

func _ExecutorService_PreviewTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).PreviewTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_PreviewTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).PreviewTool(ctx, req.(*PreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).ExecuteTool(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_GetToolRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).GetToolRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_GetToolRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).GetToolRun(ctx, req.(*GetToolRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_StreamToolRunEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExecutorServiceServer).StreamToolRunEvents(m, &grpc.GenericServerStream[StreamEventsRequest, ToolEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutorService_StreamToolRunEventsServer = grpc.ServerStreamingServer[ToolEvent]

func _ExecutorService_CancelToolRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).CancelToolRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_CancelToolRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).CancelToolRun(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecutorService_ServiceDesc is the grpc.ServiceDesc for ExecutorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanocursor.executor.ExecutorService",
	HandlerType: (*ExecutorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreviewTool",
			Handler:    _ExecutorService_PreviewTool_Handler,
		},
		{
			MethodName: "ExecuteTool",
			Handler:    _ExecutorService_ExecuteTool_Handler,
		},
		{
			MethodName: "GetToolRun",
			Handler:    _ExecutorService_GetToolRun_Handler,
		},
		{
			MethodName: "CancelToolRun",
			Handler:    _ExecutorService_CancelToolRun_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ExecutorService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamToolRunEvents",
			Handler:       _ExecutorService_StreamToolRunEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/executor.proto",
}
