// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/policy.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Policy_CheckTool_FullMethodName      = "/nanocursor.policy.Policy/CheckTool"
	Policy_CheckAction_FullMethodName    = "/nanocursor.policy.Policy/CheckAction"
	Policy_RecordResult_FullMethodName   = "/nanocursor.policy.Policy/RecordResult"
	Policy_GetPolicyState_FullMethodName = "/nanocursor.policy.Policy/GetPolicyState"
	Policy_Health_FullMethodName         = "/nanocursor.policy.Policy/Health"
)

// PolicyClient is the client API for Policy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyClient interface {
	CheckTool(ctx context.Context, in *CheckToolRequest, opts ...grpc.CallOption) (*CheckToolResponse, error)
	CheckAction(ctx context.Context, in *CheckActionRequest, opts ...grpc.CallOption) (*CheckActionResponse, error)
	RecordResult(ctx context.Context, in *RecordResultRequest, opts ...grpc.CallOption) (*RecordResultResponse, error)
	GetPolicyState(ctx context.Context, in *GetPolicyStateRequest, opts ...grpc.CallOption) (*GetPolicyStateResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type policyClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyClient(cc grpc.ClientConnInterface) PolicyClient {
	return &policyClient{cc}
}

func (c *policyClient) CheckTool(ctx context.Context, in *CheckToolRequest, opts ...grpc.CallOption) (*CheckToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckToolResponse)
	err := c.cc.Invoke(ctx, Policy_CheckTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyClient) CheckAction(ctx context.Context, in *CheckActionRequest, opts ...grpc.CallOption) (*CheckActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckActionResponse)
	err := c.cc.Invoke(ctx, Policy_CheckAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyClient) RecordResult(ctx context.Context, in *RecordResultRequest, opts ...grpc.CallOption) (*RecordResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordResultResponse)
	err := c.cc.Invoke(ctx, Policy_RecordResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyClient) GetPolicyState(ctx context.Context, in *GetPolicyStateRequest, opts ...grpc.CallOption) (*GetPolicyStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPolicyStateResponse)
	err := c.cc.Invoke(ctx, Policy_GetPolicyState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Policy_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyServer is the server API for Policy service.
// All implementations must embed UnimplementedPolicyServer
// for forward compatibility.
type PolicyServer interface {
	CheckTool(context.Context, *CheckToolRequest) (*CheckToolResponse, error)
	CheckAction(context.Context, *CheckActionRequest) (*CheckActionResponse, error)
	RecordResult(context.Context, *RecordResultRequest) (*RecordResultResponse, error)
	GetPolicyState(context.Context, *GetPolicyStateRequest) (*GetPolicyStateResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedPolicyServer()
}

// UnimplementedPolicyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyServer struct{}

func (UnimplementedPolicyServer) CheckTool(context.Context, *CheckToolRequest) (*CheckToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckTool not implemented")
}
func (UnimplementedPolicyServer) CheckAction(context.Context, *CheckActionRequest) (*CheckActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAction not implemented")
}
func (UnimplementedPolicyServer) RecordResult(context.Context, *RecordResultRequest) (*RecordResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordResult not implemented")
}
func (UnimplementedPolicyServer) GetPolicyState(context.Context, *GetPolicyStateRequest) (*GetPolicyStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolicyState not implemented")
}
func (UnimplementedPolicyServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPolicyServer) mustEmbedUnimplementedPolicyServer() {}
func (UnimplementedPolicyServer) testEmbeddedByValue()                {}

// UnsafePolicyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyServer will
// result in compilation errors.
type UnsafePolicyServer interface {
	mustEmbedUnimplementedPolicyServer()
}

func RegisterPolicyServer(s grpc.ServiceRegistrar, srv PolicyServer) {
	// If the following call panics, it indicates UnimplementedPolicyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Policy_ServiceDesc, srv)
}

func _Policy_CheckTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServer).CheckTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Policy_CheckTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServer).CheckTool(ctx, req.(*CheckToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Policy_CheckAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServer).CheckAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Policy_CheckAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServer).CheckAction(ctx, req.(*CheckActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Policy_RecordResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServer).RecordResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Policy_RecordResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServer).RecordResult(ctx, req.(*RecordResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Policy_GetPolicyState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicyStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServer).GetPolicyState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Policy_GetPolicyState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServer).GetPolicyState(ctx, req.(*GetPolicyStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Policy_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Policy_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Policy_ServiceDesc is the grpc.ServiceDesc for Policy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Policy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanocursor.policy.Policy",
	HandlerType: (*PolicyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckTool",
			Handler:    _Policy_CheckTool_Handler,
		},
		{
			MethodName: "CheckAction",
			Handler:    _Policy_CheckAction_Handler,
		},
		{
			MethodName: "RecordResult",
			Handler:    _Policy_RecordResult_Handler,
		},
		{
			MethodName: "GetPolicyState",
			Handler:    _Policy_GetPolicyState_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Policy_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/policy.proto",
}
