# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.eventstore.proto import eventstore_pb2 as eventstore__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in eventstore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventStoreServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/nanocursor.eventstore.EventStoreService/CreateSession',
                request_serializer=eventstore__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=eventstore__pb2.Session.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/nanocursor.eventstore.EventStoreService/GetSession',
                request_serializer=eventstore__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=eventstore__pb2.Session.FromString,
                _registered_method=True)
        self.UpdateSession = channel.unary_unary(
                '/nanocursor.eventstore.EventStoreService/UpdateSession',
                request_serializer=eventstore__pb2.UpdateSessionRequest.SerializeToString,
                response_deserializer=eventstore__pb2.Session.FromString,
                _registered_method=True)
        self.AppendEvent = channel.unary_unary(
                '/nanocursor.eventstore.EventStoreService/AppendEvent',
                request_serializer=eventstore__pb2.AppendEventRequest.SerializeToString,
                response_deserializer=eventstore__pb2.Event.FromString,
                _registered_method=True)
        self.ListEvents = channel.unary_unary(
                '/nanocursor.eventstore.EventStoreService/ListEvents',
                request_serializer=eventstore__pb2.ListEventsRequest.SerializeToString,
                response_deserializer=eventstore__pb2.EventList.FromString,
                _registered_method=True)
        self.CountEvents = channel.unary_unary(
                '/nanocursor.eventstore.EventStoreService/CountEvents',
                request_serializer=eventstore__pb2.CountEventsRequest.SerializeToString,
                response_deserializer=eventstore__pb2.CountEventsResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/nanocursor.eventstore.EventStoreService/SubscribeEvents',
                request_serializer=eventstore__pb2.SubscribeEventsRequest.SerializeToString,
                response_deserializer=eventstore__pb2.Event.FromString,
                _registered_method=True)
        self.WorkspaceForThread = channel.unary_unary(
                '/nanocursor.eventstore.EventStoreService/WorkspaceForThread',
                request_serializer=eventstore__pb2.WorkspaceForThreadRequest.SerializeToString,
                response_deserializer=eventstore__pb2.WorkspaceForThreadResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/nanocursor.eventstore.EventStoreService/Health',
                request_serializer=eventstore__pb2.HealthRequest.SerializeToString,
                response_deserializer=eventstore__pb2.HealthResponse.FromString,
                _registered_method=True)


class EventStoreServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WorkspaceForThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=eventstore__pb2.CreateSessionRequest.FromString,
                    response_serializer=eventstore__pb2.Session.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=eventstore__pb2.GetSessionRequest.FromString,
                    response_serializer=eventstore__pb2.Session.SerializeToString,
            ),
            'UpdateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSession,
                    request_deserializer=eventstore__pb2.UpdateSessionRequest.FromString,
                    response_serializer=eventstore__pb2.Session.SerializeToString,
            ),
            'AppendEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEvent,
                    request_deserializer=eventstore__pb2.AppendEventRequest.FromString,
                    response_serializer=eventstore__pb2.Event.SerializeToString,
            ),
            'ListEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvents,
                    request_deserializer=eventstore__pb2.ListEventsRequest.FromString,
                    response_serializer=eventstore__pb2.EventList.SerializeToString,
            ),
            'CountEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.CountEvents,
                    request_deserializer=eventstore__pb2.CountEventsRequest.FromString,
                    response_serializer=eventstore__pb2.CountEventsResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=eventstore__pb2.SubscribeEventsRequest.FromString,
                    response_serializer=eventstore__pb2.Event.SerializeToString,
            ),
            'WorkspaceForThread': grpc.unary_unary_rpc_method_handler(
                    servicer.WorkspaceForThread,
                    request_deserializer=eventstore__pb2.WorkspaceForThreadRequest.FromString,
                    response_serializer=eventstore__pb2.WorkspaceForThreadResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=eventstore__pb2.HealthRequest.FromString,
                    response_serializer=eventstore__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nanocursor.eventstore.EventStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nanocursor.eventstore.EventStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventStoreService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.eventstore.EventStoreService/CreateSession',
            eventstore__pb2.CreateSessionRequest.SerializeToString,
            eventstore__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.eventstore.EventStoreService/GetSession',
            eventstore__pb2.GetSessionRequest.SerializeToString,
            eventstore__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.eventstore.EventStoreService/UpdateSession',
            eventstore__pb2.UpdateSessionRequest.SerializeToString,
            eventstore__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.eventstore.EventStoreService/AppendEvent',
            eventstore__pb2.AppendEventRequest.SerializeToString,
            eventstore__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.eventstore.EventStoreService/ListEvents',
            eventstore__pb2.ListEventsRequest.SerializeToString,
            eventstore__pb2.EventList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.eventstore.EventStoreService/CountEvents',
            eventstore__pb2.CountEventsRequest.SerializeToString,
            eventstore__pb2.CountEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/nanocursor.eventstore.EventStoreService/SubscribeEvents',
            eventstore__pb2.SubscribeEventsRequest.SerializeToString,
            eventstore__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WorkspaceForThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.eventstore.EventStoreService/WorkspaceForThread',
            eventstore__pb2.WorkspaceForThreadRequest.SerializeToString,
            eventstore__pb2.WorkspaceForThreadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.eventstore.EventStoreService/Health',
            eventstore__pb2.HealthRequest.SerializeToString,
            eventstore__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
