// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/cron.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CronExpr      string                 `protobuf:"bytes,1,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Recurring     bool                   `protobuf:"varint,3,opt,name=recurring,proto3" json:"recurring,omitempty"`
	Durable       bool                   `protobuf:"varint,4,opt,name=durable,proto3" json:"durable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_proto_cron_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cron_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_cron_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *CreateTaskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CreateTaskRequest) GetRecurring() bool {
	if x != nil {
		return x.Recurring
	}
	return false
}

func (x *CreateTaskRequest) GetDurable() bool {
	if x != nil {
		return x.Durable
	}
	return false
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CronExpr      string                 `protobuf:"bytes,2,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Recurring     bool                   `protobuf:"varint,4,opt,name=recurring,proto3" json:"recurring,omitempty"`
	Durable       bool                   `protobuf:"varint,5,opt,name=durable,proto3" json:"durable,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastFiredAt   int64                  `protobuf:"varint,7,opt,name=last_fired_at,json=lastFiredAt,proto3" json:"last_fired_at,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_cron_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cron_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_cron_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *Task) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Task) GetRecurring() bool {
	if x != nil {
		return x.Recurring
	}
	return false
}

func (x *Task) GetDurable() bool {
	if x != nil {
		return x.Durable
	}
	return false
}

func (x *Task) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Task) GetLastFiredAt() int64 {
	if x != nil {
		return x.LastFiredAt
	}
	return 0
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_proto_cron_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cron_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_cron_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_proto_cron_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cron_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_cron_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_proto_cron_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cron_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_cron_proto_rawDescGZIP(), []int{4}
}

type TaskList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskList) Reset() {
	*x = TaskList{}
	mi := &file_proto_cron_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskList) ProtoMessage() {}

func (x *TaskList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cron_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskList.ProtoReflect.Descriptor instead.
func (*TaskList) Descriptor() ([]byte, []int) {
	return file_proto_cron_proto_rawDescGZIP(), []int{5}
}

func (x *TaskList) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type DrainEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainEventsRequest) Reset() {
	*x = DrainEventsRequest{}
	mi := &file_proto_cron_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainEventsRequest) ProtoMessage() {}

func (x *DrainEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cron_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainEventsRequest.ProtoReflect.Descriptor instead.
func (*DrainEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cron_proto_rawDescGZIP(), []int{6}
}

type CronEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Recurring     bool                   `protobuf:"varint,4,opt,name=recurring,proto3" json:"recurring,omitempty"`
	FiredAt       int64                  `protobuf:"varint,5,opt,name=fired_at,json=firedAt,proto3" json:"fired_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronEvent) Reset() {
	*x = CronEvent{}
	mi := &file_proto_cron_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronEvent) ProtoMessage() {}

func (x *CronEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cron_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronEvent.ProtoReflect.Descriptor instead.
func (*CronEvent) Descriptor() ([]byte, []int) {
	return file_proto_cron_proto_rawDescGZIP(), []int{7}
}

func (x *CronEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CronEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CronEvent) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CronEvent) GetRecurring() bool {
	if x != nil {
		return x.Recurring
	}
	return false
}

func (x *CronEvent) GetFiredAt() int64 {
	if x != nil {
		return x.FiredAt
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_cron_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cron_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_cron_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_cron_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cron_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_cron_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_cron_proto protoreflect.FileDescriptor

const file_proto_cron_proto_rawDesc = "" +
	"\n" +
	"\x10proto/cron.proto\x12\x0fnanocursor.cron\"\x80\x01\n" +
	"\x11CreateTaskRequest\x12\x1b\n" +
	"\tcron_expr\x18\x01 \x01(\tR\bcronExpr\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x1c\n" +
	"\trecurring\x18\x03 \x01(\bR\trecurring\x12\x18\n" +
	"\adurable\x18\x04 \x01(\bR\adurable\"\xde\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcron_expr\x18\x02 \x01(\tR\bcronExpr\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x1c\n" +
	"\trecurring\x18\x04 \x01(\bR\trecurring\x12\x18\n" +
	"\adurable\x18\x05 \x01(\bR\adurable\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\"\n" +
	"\rlast_fired_at\x18\a \x01(\x03R\vlastFiredAt\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\",\n" +
	"\x11DeleteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"H\n" +
	"\x12DeleteTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x12\n" +
	"\x10ListTasksRequest\"7\n" +
	"\bTaskList\x12+\n" +
	"\x05tasks\x18\x01 \x03(\v2\x15.nanocursor.cron.TaskR\x05tasks\"\x14\n" +
	"\x12DrainEventsRequest\"\x89\x01\n" +
	"\tCronEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x1c\n" +
	"\trecurring\x18\x04 \x01(\bR\trecurring\x12\x19\n" +
	"\bfired_at\x18\x05 \x01(\x03R\afiredAt\"\x0f\n" +
	"\rHealthRequest\"T\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion2\x95\x03\n" +
	"\vCronService\x12G\n" +
	"\n" +
	"CreateTask\x12\".nanocursor.cron.CreateTaskRequest\x1a\x15.nanocursor.cron.Task\x12U\n" +
	"\n" +
	"DeleteTask\x12\".nanocursor.cron.DeleteTaskRequest\x1a#.nanocursor.cron.DeleteTaskResponse\x12I\n" +
	"\tListTasks\x12!.nanocursor.cron.ListTasksRequest\x1a\x19.nanocursor.cron.TaskList\x12P\n" +
	"\vDrainEvents\x12#.nanocursor.cron.DrainEventsRequest\x1a\x1a.nanocursor.cron.CronEvent0\x01\x12I\n" +
	"\x06Health\x12\x1e.nanocursor.cron.HealthRequest\x1a\x1f.nanocursor.cron.HealthResponseB#Z!nanocursor/go-services/cron/protob\x06proto3"

var (
	file_proto_cron_proto_rawDescOnce sync.Once
	file_proto_cron_proto_rawDescData []byte
)

func file_proto_cron_proto_rawDescGZIP() []byte {
	file_proto_cron_proto_rawDescOnce.Do(func() {
		file_proto_cron_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cron_proto_rawDesc), len(file_proto_cron_proto_rawDesc)))
	})
	return file_proto_cron_proto_rawDescData
}

var file_proto_cron_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_cron_proto_goTypes = []any{
	(*CreateTaskRequest)(nil),  // 0: nanocursor.cron.CreateTaskRequest
	(*Task)(nil),               // 1: nanocursor.cron.Task
	(*DeleteTaskRequest)(nil),  // 2: nanocursor.cron.DeleteTaskRequest
	(*DeleteTaskResponse)(nil), // 3: nanocursor.cron.DeleteTaskResponse
	(*ListTasksRequest)(nil),   // 4: nanocursor.cron.ListTasksRequest
	(*TaskList)(nil),           // 5: nanocursor.cron.TaskList
	(*DrainEventsRequest)(nil), // 6: nanocursor.cron.DrainEventsRequest
	(*CronEvent)(nil),          // 7: nanocursor.cron.CronEvent
	(*HealthRequest)(nil),      // 8: nanocursor.cron.HealthRequest
	(*HealthResponse)(nil),     // 9: nanocursor.cron.HealthResponse
}
var file_proto_cron_proto_depIdxs = []int32{
	1, // 0: nanocursor.cron.TaskList.tasks:type_name -> nanocursor.cron.Task
	0, // 1: nanocursor.cron.CronService.CreateTask:input_type -> nanocursor.cron.CreateTaskRequest
	2, // 2: nanocursor.cron.CronService.DeleteTask:input_type -> nanocursor.cron.DeleteTaskRequest
	4, // 3: nanocursor.cron.CronService.ListTasks:input_type -> nanocursor.cron.ListTasksRequest
	6, // 4: nanocursor.cron.CronService.DrainEvents:input_type -> nanocursor.cron.DrainEventsRequest
	8, // 5: nanocursor.cron.CronService.Health:input_type -> nanocursor.cron.HealthRequest
	1, // 6: nanocursor.cron.CronService.CreateTask:output_type -> nanocursor.cron.Task
	3, // 7: nanocursor.cron.CronService.DeleteTask:output_type -> nanocursor.cron.DeleteTaskResponse
	5, // 8: nanocursor.cron.CronService.ListTasks:output_type -> nanocursor.cron.TaskList
	7, // 9: nanocursor.cron.CronService.DrainEvents:output_type -> nanocursor.cron.CronEvent
	9, // 10: nanocursor.cron.CronService.Health:output_type -> nanocursor.cron.HealthResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_cron_proto_init() }
func file_proto_cron_proto_init() {
	if File_proto_cron_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cron_proto_rawDesc), len(file_proto_cron_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cron_proto_goTypes,
		DependencyIndexes: file_proto_cron_proto_depIdxs,
		MessageInfos:      file_proto_cron_proto_msgTypes,
	}.Build()
	File_proto_cron_proto = out.File
	file_proto_cron_proto_goTypes = nil
	file_proto_cron_proto_depIdxs = nil
}
