# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.indexer.proto import filetools_pb2 as filetools__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in filetools_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileToolsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadFile = channel.unary_unary(
                '/nanocursor.filetools.FileTools/ReadFile',
                request_serializer=filetools__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=filetools__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.ReadFunction = channel.unary_unary(
                '/nanocursor.filetools.FileTools/ReadFunction',
                request_serializer=filetools__pb2.ReadFunctionRequest.SerializeToString,
                response_deserializer=filetools__pb2.ReadFunctionResponse.FromString,
                _registered_method=True)
        self.ReadClass = channel.unary_unary(
                '/nanocursor.filetools.FileTools/ReadClass',
                request_serializer=filetools__pb2.ReadClassRequest.SerializeToString,
                response_deserializer=filetools__pb2.ReadClassResponse.FromString,
                _registered_method=True)
        self.ReadFileRange = channel.unary_unary(
                '/nanocursor.filetools.FileTools/ReadFileRange',
                request_serializer=filetools__pb2.ReadFileRangeRequest.SerializeToString,
                response_deserializer=filetools__pb2.ReadFileRangeResponse.FromString,
                _registered_method=True)
        self.ListDirectory = channel.unary_unary(
                '/nanocursor.filetools.FileTools/ListDirectory',
                request_serializer=filetools__pb2.ListDirectoryRequest.SerializeToString,
                response_deserializer=filetools__pb2.ListDirectoryResponse.FromString,
                _registered_method=True)
        self.WriteFile = channel.unary_unary(
                '/nanocursor.filetools.FileTools/WriteFile',
                request_serializer=filetools__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=filetools__pb2.WriteFileResponse.FromString,
                _registered_method=True)
        self.EditFile = channel.unary_unary(
                '/nanocursor.filetools.FileTools/EditFile',
                request_serializer=filetools__pb2.EditFileRequest.SerializeToString,
                response_deserializer=filetools__pb2.EditFileResponse.FromString,
                _registered_method=True)
        self.BackupFile = channel.unary_unary(
                '/nanocursor.filetools.FileTools/BackupFile',
                request_serializer=filetools__pb2.BackupFileRequest.SerializeToString,
                response_deserializer=filetools__pb2.BackupFileResponse.FromString,
                _registered_method=True)
        self.RollbackFile = channel.unary_unary(
                '/nanocursor.filetools.FileTools/RollbackFile',
                request_serializer=filetools__pb2.RollbackFileRequest.SerializeToString,
                response_deserializer=filetools__pb2.RollbackFileResponse.FromString,
                _registered_method=True)
        self.ListBackups = channel.unary_unary(
                '/nanocursor.filetools.FileTools/ListBackups',
                request_serializer=filetools__pb2.ListBackupsRequest.SerializeToString,
                response_deserializer=filetools__pb2.ListBackupsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/nanocursor.filetools.FileTools/Health',
                request_serializer=filetools__pb2.HealthRequest.SerializeToString,
                response_deserializer=filetools__pb2.HealthResponse.FromString,
                _registered_method=True)


class FileToolsServicer:
    """Missing associated documentation comment in .proto file."""

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFunction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadClass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFileRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BackupFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBackups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileToolsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=filetools__pb2.ReadFileRequest.FromString,
                    response_serializer=filetools__pb2.ReadFileResponse.SerializeToString,
            ),
            'ReadFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFunction,
                    request_deserializer=filetools__pb2.ReadFunctionRequest.FromString,
                    response_serializer=filetools__pb2.ReadFunctionResponse.SerializeToString,
            ),
            'ReadClass': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadClass,
                    request_deserializer=filetools__pb2.ReadClassRequest.FromString,
                    response_serializer=filetools__pb2.ReadClassResponse.SerializeToString,
            ),
            'ReadFileRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFileRange,
                    request_deserializer=filetools__pb2.ReadFileRangeRequest.FromString,
                    response_serializer=filetools__pb2.ReadFileRangeResponse.SerializeToString,
            ),
            'ListDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDirectory,
                    request_deserializer=filetools__pb2.ListDirectoryRequest.FromString,
                    response_serializer=filetools__pb2.ListDirectoryResponse.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=filetools__pb2.WriteFileRequest.FromString,
                    response_serializer=filetools__pb2.WriteFileResponse.SerializeToString,
            ),
            'EditFile': grpc.unary_unary_rpc_method_handler(
                    servicer.EditFile,
                    request_deserializer=filetools__pb2.EditFileRequest.FromString,
                    response_serializer=filetools__pb2.EditFileResponse.SerializeToString,
            ),
            'BackupFile': grpc.unary_unary_rpc_method_handler(
                    servicer.BackupFile,
                    request_deserializer=filetools__pb2.BackupFileRequest.FromString,
                    response_serializer=filetools__pb2.BackupFileResponse.SerializeToString,
            ),
            'RollbackFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackFile,
                    request_deserializer=filetools__pb2.RollbackFileRequest.FromString,
                    response_serializer=filetools__pb2.RollbackFileResponse.SerializeToString,
            ),
            'ListBackups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBackups,
                    request_deserializer=filetools__pb2.ListBackupsRequest.FromString,
                    response_serializer=filetools__pb2.ListBackupsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=filetools__pb2.HealthRequest.FromString,
                    response_serializer=filetools__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nanocursor.filetools.FileTools', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nanocursor.filetools.FileTools', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileTools:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.filetools.FileTools/ReadFile',
            filetools__pb2.ReadFileRequest.SerializeToString,
            filetools__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.filetools.FileTools/ReadFunction',
            filetools__pb2.ReadFunctionRequest.SerializeToString,
            filetools__pb2.ReadFunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.filetools.FileTools/ReadClass',
            filetools__pb2.ReadClassRequest.SerializeToString,
            filetools__pb2.ReadClassResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFileRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.filetools.FileTools/ReadFileRange',
            filetools__pb2.ReadFileRangeRequest.SerializeToString,
            filetools__pb2.ReadFileRangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.filetools.FileTools/ListDirectory',
            filetools__pb2.ListDirectoryRequest.SerializeToString,
            filetools__pb2.ListDirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.filetools.FileTools/WriteFile',
            filetools__pb2.WriteFileRequest.SerializeToString,
            filetools__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.filetools.FileTools/EditFile',
            filetools__pb2.EditFileRequest.SerializeToString,
            filetools__pb2.EditFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BackupFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.filetools.FileTools/BackupFile',
            filetools__pb2.BackupFileRequest.SerializeToString,
            filetools__pb2.BackupFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.filetools.FileTools/RollbackFile',
            filetools__pb2.RollbackFileRequest.SerializeToString,
            filetools__pb2.RollbackFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBackups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.filetools.FileTools/ListBackups',
            filetools__pb2.ListBackupsRequest.SerializeToString,
            filetools__pb2.ListBackupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.filetools.FileTools/Health',
            filetools__pb2.HealthRequest.SerializeToString,
            filetools__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
