# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.indexer.proto import indexer_pb2 as indexer__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in indexer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IndexerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuildIndex = channel.unary_unary(
                '/nanocursor.indexer.Indexer/BuildIndex',
                request_serializer=indexer__pb2.BuildIndexRequest.SerializeToString,
                response_deserializer=indexer__pb2.BuildIndexResponse.FromString,
                _registered_method=True)
        self.UpdateIndex = channel.unary_unary(
                '/nanocursor.indexer.Indexer/UpdateIndex',
                request_serializer=indexer__pb2.UpdateIndexRequest.SerializeToString,
                response_deserializer=indexer__pb2.UpdateIndexResponse.FromString,
                _registered_method=True)
        self.SearchSymbol = channel.unary_unary(
                '/nanocursor.indexer.Indexer/SearchSymbol',
                request_serializer=indexer__pb2.SearchSymbolRequest.SerializeToString,
                response_deserializer=indexer__pb2.SearchSymbolResponse.FromString,
                _registered_method=True)
        self.SearchDependents = channel.unary_unary(
                '/nanocursor.indexer.Indexer/SearchDependents',
                request_serializer=indexer__pb2.SearchDependentsRequest.SerializeToString,
                response_deserializer=indexer__pb2.SearchDependentsResponse.FromString,
                _registered_method=True)
        self.GetSummary = channel.unary_unary(
                '/nanocursor.indexer.Indexer/GetSummary',
                request_serializer=indexer__pb2.GetSummaryRequest.SerializeToString,
                response_deserializer=indexer__pb2.GetSummaryResponse.FromString,
                _registered_method=True)
        self.GetRouteSummary = channel.unary_unary(
                '/nanocursor.indexer.Indexer/GetRouteSummary',
                request_serializer=indexer__pb2.GetRouteSummaryRequest.SerializeToString,
                response_deserializer=indexer__pb2.GetRouteSummaryResponse.FromString,
                _registered_method=True)
        self.SearchCallers = channel.unary_unary(
                '/nanocursor.indexer.Indexer/SearchCallers',
                request_serializer=indexer__pb2.SearchCallersRequest.SerializeToString,
                response_deserializer=indexer__pb2.SearchCallersResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/nanocursor.indexer.Indexer/Health',
                request_serializer=indexer__pb2.HealthRequest.SerializeToString,
                response_deserializer=indexer__pb2.HealthResponse.FromString,
                _registered_method=True)


class IndexerServicer:
    """Missing associated documentation comment in .proto file."""

    def BuildIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchSymbol(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchDependents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRouteSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchCallers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndexerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuildIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildIndex,
                    request_deserializer=indexer__pb2.BuildIndexRequest.FromString,
                    response_serializer=indexer__pb2.BuildIndexResponse.SerializeToString,
            ),
            'UpdateIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIndex,
                    request_deserializer=indexer__pb2.UpdateIndexRequest.FromString,
                    response_serializer=indexer__pb2.UpdateIndexResponse.SerializeToString,
            ),
            'SearchSymbol': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchSymbol,
                    request_deserializer=indexer__pb2.SearchSymbolRequest.FromString,
                    response_serializer=indexer__pb2.SearchSymbolResponse.SerializeToString,
            ),
            'SearchDependents': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchDependents,
                    request_deserializer=indexer__pb2.SearchDependentsRequest.FromString,
                    response_serializer=indexer__pb2.SearchDependentsResponse.SerializeToString,
            ),
            'GetSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSummary,
                    request_deserializer=indexer__pb2.GetSummaryRequest.FromString,
                    response_serializer=indexer__pb2.GetSummaryResponse.SerializeToString,
            ),
            'GetRouteSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRouteSummary,
                    request_deserializer=indexer__pb2.GetRouteSummaryRequest.FromString,
                    response_serializer=indexer__pb2.GetRouteSummaryResponse.SerializeToString,
            ),
            'SearchCallers': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchCallers,
                    request_deserializer=indexer__pb2.SearchCallersRequest.FromString,
                    response_serializer=indexer__pb2.SearchCallersResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=indexer__pb2.HealthRequest.FromString,
                    response_serializer=indexer__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nanocursor.indexer.Indexer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nanocursor.indexer.Indexer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Indexer:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BuildIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.indexer.Indexer/BuildIndex',
            indexer__pb2.BuildIndexRequest.SerializeToString,
            indexer__pb2.BuildIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.indexer.Indexer/UpdateIndex',
            indexer__pb2.UpdateIndexRequest.SerializeToString,
            indexer__pb2.UpdateIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchSymbol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.indexer.Indexer/SearchSymbol',
            indexer__pb2.SearchSymbolRequest.SerializeToString,
            indexer__pb2.SearchSymbolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchDependents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.indexer.Indexer/SearchDependents',
            indexer__pb2.SearchDependentsRequest.SerializeToString,
            indexer__pb2.SearchDependentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.indexer.Indexer/GetSummary',
            indexer__pb2.GetSummaryRequest.SerializeToString,
            indexer__pb2.GetSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRouteSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.indexer.Indexer/GetRouteSummary',
            indexer__pb2.GetRouteSummaryRequest.SerializeToString,
            indexer__pb2.GetRouteSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchCallers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.indexer.Indexer/SearchCallers',
            indexer__pb2.SearchCallersRequest.SerializeToString,
            indexer__pb2.SearchCallersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.indexer.Indexer/Health',
            indexer__pb2.HealthRequest.SerializeToString,
            indexer__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
