# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.indexer.proto import policy_pb2 as policy__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in policy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PolicyStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckTool = channel.unary_unary(
                '/nanocursor.policy.Policy/CheckTool',
                request_serializer=policy__pb2.CheckToolRequest.SerializeToString,
                response_deserializer=policy__pb2.CheckToolResponse.FromString,
                _registered_method=True)
        self.CheckAction = channel.unary_unary(
                '/nanocursor.policy.Policy/CheckAction',
                request_serializer=policy__pb2.CheckActionRequest.SerializeToString,
                response_deserializer=policy__pb2.CheckActionResponse.FromString,
                _registered_method=True)
        self.RecordResult = channel.unary_unary(
                '/nanocursor.policy.Policy/RecordResult',
                request_serializer=policy__pb2.RecordResultRequest.SerializeToString,
                response_deserializer=policy__pb2.RecordResultResponse.FromString,
                _registered_method=True)
        self.GetPolicyState = channel.unary_unary(
                '/nanocursor.policy.Policy/GetPolicyState',
                request_serializer=policy__pb2.GetPolicyStateRequest.SerializeToString,
                response_deserializer=policy__pb2.GetPolicyStateResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/nanocursor.policy.Policy/Health',
                request_serializer=policy__pb2.HealthRequest.SerializeToString,
                response_deserializer=policy__pb2.HealthResponse.FromString,
                _registered_method=True)


class PolicyServicer:
    """Missing associated documentation comment in .proto file."""

    def CheckTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicyState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckTool,
                    request_deserializer=policy__pb2.CheckToolRequest.FromString,
                    response_serializer=policy__pb2.CheckToolResponse.SerializeToString,
            ),
            'CheckAction': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAction,
                    request_deserializer=policy__pb2.CheckActionRequest.FromString,
                    response_serializer=policy__pb2.CheckActionResponse.SerializeToString,
            ),
            'RecordResult': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordResult,
                    request_deserializer=policy__pb2.RecordResultRequest.FromString,
                    response_serializer=policy__pb2.RecordResultResponse.SerializeToString,
            ),
            'GetPolicyState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicyState,
                    request_deserializer=policy__pb2.GetPolicyStateRequest.FromString,
                    response_serializer=policy__pb2.GetPolicyStateResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=policy__pb2.HealthRequest.FromString,
                    response_serializer=policy__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nanocursor.policy.Policy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nanocursor.policy.Policy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Policy:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.policy.Policy/CheckTool',
            policy__pb2.CheckToolRequest.SerializeToString,
            policy__pb2.CheckToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.policy.Policy/CheckAction',
            policy__pb2.CheckActionRequest.SerializeToString,
            policy__pb2.CheckActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.policy.Policy/RecordResult',
            policy__pb2.RecordResultRequest.SerializeToString,
            policy__pb2.RecordResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicyState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.policy.Policy/GetPolicyState',
            policy__pb2.GetPolicyStateRequest.SerializeToString,
            policy__pb2.GetPolicyStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.policy.Policy/Health',
            policy__pb2.HealthRequest.SerializeToString,
            policy__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
