# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.indexer.proto import taskboard_pb2 as taskboard__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in taskboard_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskBoardStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTask = channel.unary_unary(
                '/nanocursor.taskboard.TaskBoard/AddTask',
                request_serializer=taskboard__pb2.AddTaskRequest.SerializeToString,
                response_deserializer=taskboard__pb2.AddTaskResponse.FromString,
                _registered_method=True)
        self.UpdateTask = channel.unary_unary(
                '/nanocursor.taskboard.TaskBoard/UpdateTask',
                request_serializer=taskboard__pb2.UpdateTaskRequest.SerializeToString,
                response_deserializer=taskboard__pb2.UpdateTaskResponse.FromString,
                _registered_method=True)
        self.RemoveTask = channel.unary_unary(
                '/nanocursor.taskboard.TaskBoard/RemoveTask',
                request_serializer=taskboard__pb2.RemoveTaskRequest.SerializeToString,
                response_deserializer=taskboard__pb2.RemoveTaskResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/nanocursor.taskboard.TaskBoard/GetTask',
                request_serializer=taskboard__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=taskboard__pb2.GetTaskResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/nanocursor.taskboard.TaskBoard/ListTasks',
                request_serializer=taskboard__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=taskboard__pb2.ListTasksResponse.FromString,
                _registered_method=True)
        self.ApplyTaskStatus = channel.unary_unary(
                '/nanocursor.taskboard.TaskBoard/ApplyTaskStatus',
                request_serializer=taskboard__pb2.ApplyTaskStatusRequest.SerializeToString,
                response_deserializer=taskboard__pb2.ApplyTaskStatusResponse.FromString,
                _registered_method=True)
        self.GetReadyNodes = channel.unary_unary(
                '/nanocursor.taskboard.TaskBoard/GetReadyNodes',
                request_serializer=taskboard__pb2.GetReadyNodesRequest.SerializeToString,
                response_deserializer=taskboard__pb2.GetReadyNodesResponse.FromString,
                _registered_method=True)
        self.ConnectTasks = channel.unary_unary(
                '/nanocursor.taskboard.TaskBoard/ConnectTasks',
                request_serializer=taskboard__pb2.ConnectTasksRequest.SerializeToString,
                response_deserializer=taskboard__pb2.ConnectTasksResponse.FromString,
                _registered_method=True)
        self.DisconnectTasks = channel.unary_unary(
                '/nanocursor.taskboard.TaskBoard/DisconnectTasks',
                request_serializer=taskboard__pb2.DisconnectTasksRequest.SerializeToString,
                response_deserializer=taskboard__pb2.DisconnectTasksResponse.FromString,
                _registered_method=True)
        self.SaveBoard = channel.unary_unary(
                '/nanocursor.taskboard.TaskBoard/SaveBoard',
                request_serializer=taskboard__pb2.SaveBoardRequest.SerializeToString,
                response_deserializer=taskboard__pb2.SaveBoardResponse.FromString,
                _registered_method=True)
        self.LoadBoard = channel.unary_unary(
                '/nanocursor.taskboard.TaskBoard/LoadBoard',
                request_serializer=taskboard__pb2.LoadBoardRequest.SerializeToString,
                response_deserializer=taskboard__pb2.LoadBoardResponse.FromString,
                _registered_method=True)
        self.BuildBoard = channel.unary_unary(
                '/nanocursor.taskboard.TaskBoard/BuildBoard',
                request_serializer=taskboard__pb2.BuildBoardRequest.SerializeToString,
                response_deserializer=taskboard__pb2.BuildBoardResponse.FromString,
                _registered_method=True)
        self.GetBoardState = channel.unary_unary(
                '/nanocursor.taskboard.TaskBoard/GetBoardState',
                request_serializer=taskboard__pb2.GetBoardStateRequest.SerializeToString,
                response_deserializer=taskboard__pb2.GetBoardStateResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/nanocursor.taskboard.TaskBoard/Health',
                request_serializer=taskboard__pb2.HealthRequest.SerializeToString,
                response_deserializer=taskboard__pb2.HealthResponse.FromString,
                _registered_method=True)


class TaskBoardServicer:
    """Missing associated documentation comment in .proto file."""

    def AddTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyTaskStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReadyNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveBoard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadBoard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildBoard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBoardState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskBoardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTask,
                    request_deserializer=taskboard__pb2.AddTaskRequest.FromString,
                    response_serializer=taskboard__pb2.AddTaskResponse.SerializeToString,
            ),
            'UpdateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTask,
                    request_deserializer=taskboard__pb2.UpdateTaskRequest.FromString,
                    response_serializer=taskboard__pb2.UpdateTaskResponse.SerializeToString,
            ),
            'RemoveTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTask,
                    request_deserializer=taskboard__pb2.RemoveTaskRequest.FromString,
                    response_serializer=taskboard__pb2.RemoveTaskResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=taskboard__pb2.GetTaskRequest.FromString,
                    response_serializer=taskboard__pb2.GetTaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=taskboard__pb2.ListTasksRequest.FromString,
                    response_serializer=taskboard__pb2.ListTasksResponse.SerializeToString,
            ),
            'ApplyTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyTaskStatus,
                    request_deserializer=taskboard__pb2.ApplyTaskStatusRequest.FromString,
                    response_serializer=taskboard__pb2.ApplyTaskStatusResponse.SerializeToString,
            ),
            'GetReadyNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReadyNodes,
                    request_deserializer=taskboard__pb2.GetReadyNodesRequest.FromString,
                    response_serializer=taskboard__pb2.GetReadyNodesResponse.SerializeToString,
            ),
            'ConnectTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectTasks,
                    request_deserializer=taskboard__pb2.ConnectTasksRequest.FromString,
                    response_serializer=taskboard__pb2.ConnectTasksResponse.SerializeToString,
            ),
            'DisconnectTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectTasks,
                    request_deserializer=taskboard__pb2.DisconnectTasksRequest.FromString,
                    response_serializer=taskboard__pb2.DisconnectTasksResponse.SerializeToString,
            ),
            'SaveBoard': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveBoard,
                    request_deserializer=taskboard__pb2.SaveBoardRequest.FromString,
                    response_serializer=taskboard__pb2.SaveBoardResponse.SerializeToString,
            ),
            'LoadBoard': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadBoard,
                    request_deserializer=taskboard__pb2.LoadBoardRequest.FromString,
                    response_serializer=taskboard__pb2.LoadBoardResponse.SerializeToString,
            ),
            'BuildBoard': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildBoard,
                    request_deserializer=taskboard__pb2.BuildBoardRequest.FromString,
                    response_serializer=taskboard__pb2.BuildBoardResponse.SerializeToString,
            ),
            'GetBoardState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBoardState,
                    request_deserializer=taskboard__pb2.GetBoardStateRequest.FromString,
                    response_serializer=taskboard__pb2.GetBoardStateResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=taskboard__pb2.HealthRequest.FromString,
                    response_serializer=taskboard__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nanocursor.taskboard.TaskBoard', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nanocursor.taskboard.TaskBoard', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskBoard:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.taskboard.TaskBoard/AddTask',
            taskboard__pb2.AddTaskRequest.SerializeToString,
            taskboard__pb2.AddTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.taskboard.TaskBoard/UpdateTask',
            taskboard__pb2.UpdateTaskRequest.SerializeToString,
            taskboard__pb2.UpdateTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.taskboard.TaskBoard/RemoveTask',
            taskboard__pb2.RemoveTaskRequest.SerializeToString,
            taskboard__pb2.RemoveTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.taskboard.TaskBoard/GetTask',
            taskboard__pb2.GetTaskRequest.SerializeToString,
            taskboard__pb2.GetTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.taskboard.TaskBoard/ListTasks',
            taskboard__pb2.ListTasksRequest.SerializeToString,
            taskboard__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.taskboard.TaskBoard/ApplyTaskStatus',
            taskboard__pb2.ApplyTaskStatusRequest.SerializeToString,
            taskboard__pb2.ApplyTaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReadyNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.taskboard.TaskBoard/GetReadyNodes',
            taskboard__pb2.GetReadyNodesRequest.SerializeToString,
            taskboard__pb2.GetReadyNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.taskboard.TaskBoard/ConnectTasks',
            taskboard__pb2.ConnectTasksRequest.SerializeToString,
            taskboard__pb2.ConnectTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisconnectTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.taskboard.TaskBoard/DisconnectTasks',
            taskboard__pb2.DisconnectTasksRequest.SerializeToString,
            taskboard__pb2.DisconnectTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveBoard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.taskboard.TaskBoard/SaveBoard',
            taskboard__pb2.SaveBoardRequest.SerializeToString,
            taskboard__pb2.SaveBoardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadBoard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.taskboard.TaskBoard/LoadBoard',
            taskboard__pb2.LoadBoardRequest.SerializeToString,
            taskboard__pb2.LoadBoardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildBoard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.taskboard.TaskBoard/BuildBoard',
            taskboard__pb2.BuildBoardRequest.SerializeToString,
            taskboard__pb2.BuildBoardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBoardState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.taskboard.TaskBoard/GetBoardState',
            taskboard__pb2.GetBoardStateRequest.SerializeToString,
            taskboard__pb2.GetBoardStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.taskboard.TaskBoard/Health',
            taskboard__pb2.HealthRequest.SerializeToString,
            taskboard__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
