// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: indexer.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Indexer_BuildIndex_FullMethodName       = "/nanocursor.indexer.Indexer/BuildIndex"
	Indexer_UpdateIndex_FullMethodName      = "/nanocursor.indexer.Indexer/UpdateIndex"
	Indexer_SearchSymbol_FullMethodName     = "/nanocursor.indexer.Indexer/SearchSymbol"
	Indexer_SearchDependents_FullMethodName = "/nanocursor.indexer.Indexer/SearchDependents"
	Indexer_GetSummary_FullMethodName       = "/nanocursor.indexer.Indexer/GetSummary"
	Indexer_GetRouteSummary_FullMethodName  = "/nanocursor.indexer.Indexer/GetRouteSummary"
	Indexer_SearchCallers_FullMethodName    = "/nanocursor.indexer.Indexer/SearchCallers"
	Indexer_Health_FullMethodName           = "/nanocursor.indexer.Indexer/Health"
)

// IndexerClient is the client API for Indexer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IndexerClient interface {
	BuildIndex(ctx context.Context, in *BuildIndexRequest, opts ...grpc.CallOption) (*BuildIndexResponse, error)
	UpdateIndex(ctx context.Context, in *UpdateIndexRequest, opts ...grpc.CallOption) (*UpdateIndexResponse, error)
	SearchSymbol(ctx context.Context, in *SearchSymbolRequest, opts ...grpc.CallOption) (*SearchSymbolResponse, error)
	SearchDependents(ctx context.Context, in *SearchDependentsRequest, opts ...grpc.CallOption) (*SearchDependentsResponse, error)
	GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*GetSummaryResponse, error)
	GetRouteSummary(ctx context.Context, in *GetRouteSummaryRequest, opts ...grpc.CallOption) (*GetRouteSummaryResponse, error)
	SearchCallers(ctx context.Context, in *SearchCallersRequest, opts ...grpc.CallOption) (*SearchCallersResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type indexerClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexerClient(cc grpc.ClientConnInterface) IndexerClient {
	return &indexerClient{cc}
}

func (c *indexerClient) BuildIndex(ctx context.Context, in *BuildIndexRequest, opts ...grpc.CallOption) (*BuildIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildIndexResponse)
	err := c.cc.Invoke(ctx, Indexer_BuildIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexerClient) UpdateIndex(ctx context.Context, in *UpdateIndexRequest, opts ...grpc.CallOption) (*UpdateIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateIndexResponse)
	err := c.cc.Invoke(ctx, Indexer_UpdateIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexerClient) SearchSymbol(ctx context.Context, in *SearchSymbolRequest, opts ...grpc.CallOption) (*SearchSymbolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchSymbolResponse)
	err := c.cc.Invoke(ctx, Indexer_SearchSymbol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexerClient) SearchDependents(ctx context.Context, in *SearchDependentsRequest, opts ...grpc.CallOption) (*SearchDependentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchDependentsResponse)
	err := c.cc.Invoke(ctx, Indexer_SearchDependents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexerClient) GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*GetSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSummaryResponse)
	err := c.cc.Invoke(ctx, Indexer_GetSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexerClient) GetRouteSummary(ctx context.Context, in *GetRouteSummaryRequest, opts ...grpc.CallOption) (*GetRouteSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteSummaryResponse)
	err := c.cc.Invoke(ctx, Indexer_GetRouteSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexerClient) SearchCallers(ctx context.Context, in *SearchCallersRequest, opts ...grpc.CallOption) (*SearchCallersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchCallersResponse)
	err := c.cc.Invoke(ctx, Indexer_SearchCallers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexerClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Indexer_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexerServer is the server API for Indexer service.
// All implementations must embed UnimplementedIndexerServer
// for forward compatibility.
type IndexerServer interface {
	BuildIndex(context.Context, *BuildIndexRequest) (*BuildIndexResponse, error)
	UpdateIndex(context.Context, *UpdateIndexRequest) (*UpdateIndexResponse, error)
	SearchSymbol(context.Context, *SearchSymbolRequest) (*SearchSymbolResponse, error)
	SearchDependents(context.Context, *SearchDependentsRequest) (*SearchDependentsResponse, error)
	GetSummary(context.Context, *GetSummaryRequest) (*GetSummaryResponse, error)
	GetRouteSummary(context.Context, *GetRouteSummaryRequest) (*GetRouteSummaryResponse, error)
	SearchCallers(context.Context, *SearchCallersRequest) (*SearchCallersResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedIndexerServer()
}

// UnimplementedIndexerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndexerServer struct{}

func (UnimplementedIndexerServer) BuildIndex(context.Context, *BuildIndexRequest) (*BuildIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildIndex not implemented")
}
func (UnimplementedIndexerServer) UpdateIndex(context.Context, *UpdateIndexRequest) (*UpdateIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateIndex not implemented")
}
func (UnimplementedIndexerServer) SearchSymbol(context.Context, *SearchSymbolRequest) (*SearchSymbolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSymbol not implemented")
}
func (UnimplementedIndexerServer) SearchDependents(context.Context, *SearchDependentsRequest) (*SearchDependentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchDependents not implemented")
}
func (UnimplementedIndexerServer) GetSummary(context.Context, *GetSummaryRequest) (*GetSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSummary not implemented")
}
func (UnimplementedIndexerServer) GetRouteSummary(context.Context, *GetRouteSummaryRequest) (*GetRouteSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRouteSummary not implemented")
}
func (UnimplementedIndexerServer) SearchCallers(context.Context, *SearchCallersRequest) (*SearchCallersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchCallers not implemented")
}
func (UnimplementedIndexerServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedIndexerServer) mustEmbedUnimplementedIndexerServer() {}
func (UnimplementedIndexerServer) testEmbeddedByValue()                 {}

// UnsafeIndexerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexerServer will
// result in compilation errors.
type UnsafeIndexerServer interface {
	mustEmbedUnimplementedIndexerServer()
}

func RegisterIndexerServer(s grpc.ServiceRegistrar, srv IndexerServer) {
	// If the following call panics, it indicates UnimplementedIndexerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Indexer_ServiceDesc, srv)
}

func _Indexer_BuildIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServer).BuildIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Indexer_BuildIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServer).BuildIndex(ctx, req.(*BuildIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indexer_UpdateIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServer).UpdateIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Indexer_UpdateIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServer).UpdateIndex(ctx, req.(*UpdateIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indexer_SearchSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServer).SearchSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Indexer_SearchSymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServer).SearchSymbol(ctx, req.(*SearchSymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indexer_SearchDependents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDependentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServer).SearchDependents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Indexer_SearchDependents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServer).SearchDependents(ctx, req.(*SearchDependentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indexer_GetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServer).GetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Indexer_GetSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServer).GetSummary(ctx, req.(*GetSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indexer_GetRouteSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServer).GetRouteSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Indexer_GetRouteSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServer).GetRouteSummary(ctx, req.(*GetRouteSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indexer_SearchCallers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCallersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServer).SearchCallers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Indexer_SearchCallers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServer).SearchCallers(ctx, req.(*SearchCallersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indexer_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Indexer_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Indexer_ServiceDesc is the grpc.ServiceDesc for Indexer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Indexer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanocursor.indexer.Indexer",
	HandlerType: (*IndexerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuildIndex",
			Handler:    _Indexer_BuildIndex_Handler,
		},
		{
			MethodName: "UpdateIndex",
			Handler:    _Indexer_UpdateIndex_Handler,
		},
		{
			MethodName: "SearchSymbol",
			Handler:    _Indexer_SearchSymbol_Handler,
		},
		{
			MethodName: "SearchDependents",
			Handler:    _Indexer_SearchDependents_Handler,
		},
		{
			MethodName: "GetSummary",
			Handler:    _Indexer_GetSummary_Handler,
		},
		{
			MethodName: "GetRouteSummary",
			Handler:    _Indexer_GetRouteSummary_Handler,
		},
		{
			MethodName: "SearchCallers",
			Handler:    _Indexer_SearchCallers_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Indexer_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "indexer.proto",
}
