# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.cron.proto import cron_pb2 as cron__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cron_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CronServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/nanocursor.cron.CronService/CreateTask',
                request_serializer=cron__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=cron__pb2.Task.FromString,
                _registered_method=True)
        self.DeleteTask = channel.unary_unary(
                '/nanocursor.cron.CronService/DeleteTask',
                request_serializer=cron__pb2.DeleteTaskRequest.SerializeToString,
                response_deserializer=cron__pb2.DeleteTaskResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/nanocursor.cron.CronService/ListTasks',
                request_serializer=cron__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=cron__pb2.TaskList.FromString,
                _registered_method=True)
        self.DrainEvents = channel.unary_stream(
                '/nanocursor.cron.CronService/DrainEvents',
                request_serializer=cron__pb2.DrainEventsRequest.SerializeToString,
                response_deserializer=cron__pb2.CronEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/nanocursor.cron.CronService/Health',
                request_serializer=cron__pb2.HealthRequest.SerializeToString,
                response_deserializer=cron__pb2.HealthResponse.FromString,
                _registered_method=True)


class CronServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DrainEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CronServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=cron__pb2.CreateTaskRequest.FromString,
                    response_serializer=cron__pb2.Task.SerializeToString,
            ),
            'DeleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTask,
                    request_deserializer=cron__pb2.DeleteTaskRequest.FromString,
                    response_serializer=cron__pb2.DeleteTaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=cron__pb2.ListTasksRequest.FromString,
                    response_serializer=cron__pb2.TaskList.SerializeToString,
            ),
            'DrainEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.DrainEvents,
                    request_deserializer=cron__pb2.DrainEventsRequest.FromString,
                    response_serializer=cron__pb2.CronEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=cron__pb2.HealthRequest.FromString,
                    response_serializer=cron__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nanocursor.cron.CronService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nanocursor.cron.CronService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CronService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.cron.CronService/CreateTask',
            cron__pb2.CreateTaskRequest.SerializeToString,
            cron__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.cron.CronService/DeleteTask',
            cron__pb2.DeleteTaskRequest.SerializeToString,
            cron__pb2.DeleteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.cron.CronService/ListTasks',
            cron__pb2.ListTasksRequest.SerializeToString,
            cron__pb2.TaskList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DrainEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/nanocursor.cron.CronService/DrainEvents',
            cron__pb2.DrainEventsRequest.SerializeToString,
            cron__pb2.CronEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.cron.CronService/Health',
            cron__pb2.HealthRequest.SerializeToString,
            cron__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
