#!/usr/bin/env python3
"""Backend API audit script — generates docs/backend-audit-report.md.

Traverses all registered routes, checks for duplicates, identifies routes that
are still defined in api_server.py, and flags routes using bare dict parameters.
"""

from __future__ import annotations

import inspect
import os
import sys
from collections import defaultdict
from pathlib import Path

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from api_server import app


def collect_routes():
    """Collect all routes from the FastAPI app."""
    routes_info: list[dict] = []
    seen = set()

    for route in app.routes:
        path = getattr(route, "path", "")
        methods = tuple(sorted(getattr(route, "methods", []) or []))
        endpoint = getattr(route, "endpoint", None)
        name = getattr(route, "name", getattr(endpoint, "__name__", str(route)))

        # Skip duplicates (mounted sub-apps may register twice)
        key = (path, methods, name)
        if key in seen:
            continue
        seen.add(key)

        module = ""
        file_path = ""
        if endpoint:
            try:
                module = inspect.getmodule(endpoint).__name__ if inspect.getmodule(endpoint) else ""
                file_path = inspect.getfile(endpoint)
            except (TypeError, OSError):
                pass

        routes_info.append({
            "path": path,
            "methods": list(methods),
            "name": name,
            "module": module,
            "file": file_path,
            "in_api_server": "api_server.py" in file_path,
        })

    return routes_info


def find_duplicates(routes: list[dict]):
    """Find duplicate (path, methods) registrations."""
    groups = defaultdict(list)
    for r in routes:
        key = (r["path"], tuple(sorted(r["methods"])))
        groups[key].append(r)

    return {k: v for k, v in groups.items() if len(v) > 1}


def find_bare_dict_routes(routes: list[dict]):
    """Find routes whose handler accepts a bare dict parameter."""
    bare = []
    for r in routes:
        endpoint = None
        for route in app.routes:
            if getattr(route, "name", None) == r["name"]:
                endpoint = getattr(route, "endpoint", None)
                break
        if not endpoint:
            continue
        try:
            sig = inspect.signature(endpoint)
        except (ValueError, TypeError):
            continue
        for param_name, param in sig.parameters.items():
            if param_name in ("request", "req"):
                continue
            ann = param.annotation
            if ann is inspect.Parameter.empty:
                continue
            if ann is dict:
                bare.append({**r, "param": param_name})
                break
    return bare


def generate_report(routes: list[dict], duplicates: dict, bare_dict: list[dict]):
    """Generate Markdown report."""
    api_routes = [r for r in routes if r["path"].startswith("/api/")]
    non_api_routes = [r for r in routes if not r["path"].startswith("/api/")]

    in_server = [r for r in api_routes if r["in_api_server"]]
    modular = [r for r in api_routes if not r["in_api_server"]]

    lines = [
        "# nanoCursor Backend API Audit Report",
        "",
        f"> Generated by `scripts/backend_audit.py`",
        f"> Total routes: {len(routes)}  |  API routes: {len(api_routes)}  |  In api_server.py: {len(in_server)}",
        "",
        "## Summary",
        "",
        f"| Metric | Count |",
        f"|---|---|",
        f"| Total registered routes | {len(routes)} |",
        f"| API routes (`/api/*`) | {len(api_routes)} |",
        f"| Non-API routes (health, mounts) | {len(non_api_routes)} |",
        f"| Routes still in `api_server.py` | {len(in_server)} |",
        f"| Routes in modular `src/api/routes/*` | {len(modular)} |",
        f"| Duplicate route groups | {len(duplicates)} |",
        f"| Routes with bare `dict` parameter | {len(bare_dict)} |",
        "",
    ]

    if duplicates:
        lines.append("## Duplicate Routes (ERROR)")
        lines.append("")
        for (path, methods), entries in duplicates.items():
            methods_str = ", ".join(methods) if methods else "ANY"
            lines.append(f"### `{methods_str} {path}`")
            for e in entries:
                lines.append(f"- `{e['name']}` in `{e['module'] or 'unknown'}`")
            lines.append("")
    else:
        lines.append("## Duplicate Routes")
        lines.append("")
        lines.append("No duplicate routes found.")
        lines.append("")

    if bare_dict:
        lines.append("## Routes with Bare `dict` Parameters (WARNING)")
        lines.append("")
        lines.append("These routes should be migrated to Pydantic request models:")
        lines.append("")
        lines.append("| Method | Path | Handler | Param | File |")
        lines.append("|---|---|---|---|---|")
        for r in bare_dict:
            methods = ", ".join(r["methods"])
            lines.append(f"| {methods} | `{r['path']}` | `{r['name']}` | `{r.get('param', '?')}` | `{r['module']}` |")
        lines.append("")
    else:
        lines.append("## Routes with Bare `dict` Parameters")
        lines.append("")
        lines.append("No bare dict parameters found in API routes.")
        lines.append("")

    lines.append("## Routes in `api_server.py` (Not Yet Modularized)")
    lines.append("")
    if in_server:
        lines.append("| Method | Path | Handler |")
        lines.append("|---|---|---|")
        for r in sorted(in_server, key=lambda x: x["path"]):
            methods = ", ".join(r["methods"])
            lines.append(f"| {methods} | `{r['path']}` | `{r['name']}` |")
    else:
        lines.append("All routes are modularized.")
    lines.append("")

    lines.append("## Modular Routes (in `src/api/routes/*`)")
    lines.append("")
    if modular:
        by_module = defaultdict(list)
        for r in modular:
            by_module[r["module"]].append(r)
        for mod, mod_routes in sorted(by_module.items()):
            lines.append(f"### `{mod}`")
            lines.append("")
            lines.append("| Method | Path | Handler |")
            lines.append("|---|---|---|")
            for r in sorted(mod_routes, key=lambda x: x["path"]):
                methods = ", ".join(r["methods"])
                lines.append(f"| {methods} | `{r['path']}` | `{r['name']}` |")
            lines.append("")
    else:
        lines.append("No modular routes yet.")
    lines.append("")

    lines.append("## Non-API Routes")
    lines.append("")
    lines.append("| Method | Path | Name |")
    lines.append("|---|---|---|")
    for r in non_api_routes:
        methods = ", ".join(r["methods"])
        lines.append(f"| {methods} | `{r['path']}` | `{r['name']}` |")
    lines.append("")

    lines.append("## Full API Route Inventory")
    lines.append("")
    lines.append("| Method | Path | Handler | Module | In api_server.py? |")
    lines.append("|---|---|---|---|---|")
    for r in sorted(api_routes, key=lambda x: (x["path"], ", ".join(x["methods"]))):
        methods = ", ".join(r["methods"]) if r["methods"] else "ANY"
        lines.append(f"| {methods} | `{r['path']}` | `{r['name']}` | `{r['module'] or 'unknown'}` | {'YES' if r['in_api_server'] else 'no'} |")
    lines.append("")

    return "\n".join(lines)


def main():
    routes = collect_routes()
    duplicates = find_duplicates(routes)
    bare_dict = find_bare_dict_routes(routes)

    report = generate_report(routes, duplicates, bare_dict)

    docs_dir = Path(ROOT) / "docs"
    docs_dir.mkdir(exist_ok=True)
    report_path = docs_dir / "backend-audit-report.md"
    report_path.write_text(report, encoding="utf-8")

    print(f"Audit complete. Report written to {report_path}")
    print(f"  Total routes: {len(routes)}")
    print(f"  API routes: {len([r for r in routes if r['path'].startswith('/api/')])}")
    print(f"  In api_server.py: {len([r for r in routes if r['in_api_server']])}")
    print(f"  Duplicates: {len(duplicates)}")
    print(f"  Bare dict params: {len(bare_dict)}")

    if duplicates:
        print("\n  DUPLICATE ROUTES FOUND:")
        for (path, methods), entries in duplicates.items():
            print(f"    {methods} {path}")
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
