# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.executor.proto import executor_pb2 as executor__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in executor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecutorServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PreviewTool = channel.unary_unary(
                '/nanocursor.executor.ExecutorService/PreviewTool',
                request_serializer=executor__pb2.PreviewRequest.SerializeToString,
                response_deserializer=executor__pb2.Decision.FromString,
                _registered_method=True)
        self.ExecuteTool = channel.unary_unary(
                '/nanocursor.executor.ExecutorService/ExecuteTool',
                request_serializer=executor__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=executor__pb2.ToolRun.FromString,
                _registered_method=True)
        self.GetToolRun = channel.unary_unary(
                '/nanocursor.executor.ExecutorService/GetToolRun',
                request_serializer=executor__pb2.GetToolRunRequest.SerializeToString,
                response_deserializer=executor__pb2.ToolRun.FromString,
                _registered_method=True)
        self.StreamToolRunEvents = channel.unary_stream(
                '/nanocursor.executor.ExecutorService/StreamToolRunEvents',
                request_serializer=executor__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=executor__pb2.ToolEvent.FromString,
                _registered_method=True)
        self.CancelToolRun = channel.unary_unary(
                '/nanocursor.executor.ExecutorService/CancelToolRun',
                request_serializer=executor__pb2.CancelRequest.SerializeToString,
                response_deserializer=executor__pb2.CancelResult.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/nanocursor.executor.ExecutorService/Health',
                request_serializer=executor__pb2.HealthRequest.SerializeToString,
                response_deserializer=executor__pb2.HealthResponse.FromString,
                _registered_method=True)


class ExecutorServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PreviewTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetToolRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamToolRunEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelToolRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PreviewTool': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewTool,
                    request_deserializer=executor__pb2.PreviewRequest.FromString,
                    response_serializer=executor__pb2.Decision.SerializeToString,
            ),
            'ExecuteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTool,
                    request_deserializer=executor__pb2.ExecuteRequest.FromString,
                    response_serializer=executor__pb2.ToolRun.SerializeToString,
            ),
            'GetToolRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToolRun,
                    request_deserializer=executor__pb2.GetToolRunRequest.FromString,
                    response_serializer=executor__pb2.ToolRun.SerializeToString,
            ),
            'StreamToolRunEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamToolRunEvents,
                    request_deserializer=executor__pb2.StreamEventsRequest.FromString,
                    response_serializer=executor__pb2.ToolEvent.SerializeToString,
            ),
            'CancelToolRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelToolRun,
                    request_deserializer=executor__pb2.CancelRequest.FromString,
                    response_serializer=executor__pb2.CancelResult.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=executor__pb2.HealthRequest.FromString,
                    response_serializer=executor__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nanocursor.executor.ExecutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nanocursor.executor.ExecutorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExecutorService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PreviewTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.executor.ExecutorService/PreviewTool',
            executor__pb2.PreviewRequest.SerializeToString,
            executor__pb2.Decision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.executor.ExecutorService/ExecuteTool',
            executor__pb2.ExecuteRequest.SerializeToString,
            executor__pb2.ToolRun.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetToolRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.executor.ExecutorService/GetToolRun',
            executor__pb2.GetToolRunRequest.SerializeToString,
            executor__pb2.ToolRun.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamToolRunEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/nanocursor.executor.ExecutorService/StreamToolRunEvents',
            executor__pb2.StreamEventsRequest.SerializeToString,
            executor__pb2.ToolEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelToolRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.executor.ExecutorService/CancelToolRun',
            executor__pb2.CancelRequest.SerializeToString,
            executor__pb2.CancelResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanocursor.executor.ExecutorService/Health',
            executor__pb2.HealthRequest.SerializeToString,
            executor__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
