import { STORAGE_KEYS, getStorageValue, loadLayoutPreference } from "../core/storage.js";

const RECOMMENDATION_MUTED_KEY = STORAGE_KEYS.recommendationMuted;

export const demoState = {
  status: "idle",
  activeTab: "report",
  leftTab: "runs",
  rightTab: "tasks",
  currentThreadId: "demo-run",
  currentConversationId: "",
  workspaceDir: getStorageValue("workspaceDir") || "",
  workspaceInput: getStorageValue("workspaceDir") || "",
  projectOverview: {
    workspace_dir: getStorageValue("workspaceDir") || "",
    summary: {
      conversation_count: 0,
      recent_run_count: 0,
      failed_run_count: 0,
      skill_count: 2,
      custom_skill_count: 0,
      configured_mcp_count: 0,
      recovery_point_count: 1,
      risk_count: 0,
      source_count: 0,
      test_count: 0,
      route_count: 0,
    },
    project_index: {
      status: "demo",
      entry_points: ["api_server.py", "frontend/src/main.js"],
      total_files: 0,
      source_count: 0,
      test_count: 0,
      total_loc: 0,
      recently_modified: [],
      routes: [],
      route_count: 0,
    },
    recent_conversations: [],
    recent_runs: [],
    skills: [],
    mcp: [],
    recovery: {
      status: "safe",
      summary: {},
      recent_points: [],
      risks: [],
      actions: [],
    },
  },
  workspaceMeta: {
    default_workspace: "",
    workspace_root: "",
    project_root: "",
    is_default_workspace: false,
  },
  ui: {
    busyActions: {},
    toast: null,
    workspacePickerOpen: false,
    recommendationExpanded: false,
    commandPaletteOpen: false,
    commandQuery: "",
    layoutMode: getStorageValue("layoutMode") || "workbench",
  },
  layout: loadLayoutPreference(),
  prompt:
    "帮我做一个 Todo Web App，要求支持新增、完成、删除、搜索和本地存储，并给出测试说明。",
  replay: {
    events: [],
    index: 0,
    speed: 1,
    status: "idle",
    prompt: "",
    startedAt: "",
  },
  approval: {
    status: "idle",
    planId: "",
    title: "",
    content: "",
    riskLevel: "",
    tasks: [],
    decision: "",
    comment: "",
  },
  runs: [
    {
      id: "demo-run",
      title: "Todo Web App 交付",
      status: "completed",
      time: "14:20",
    },
    {
      id: "python-feature",
      title: "Python 工具补测试",
      status: "review",
      time: "昨天",
    },
  ],
  conversations: [],
  messages: [
    {
      role: "user",
      author: "用户",
      time: "14:20",
      content:
        "帮我做一个 Todo Web App，要求支持新增、完成、删除、搜索和本地存储，并给出测试说明。",
    },
    {
      role: "assistant",
      author: "Lead Agent",
      time: "14:20",
      content:
        "我会按 nanoCursor 交付流程执行：先拆解需求，再由 Coder 生成前端实现，Tester 验证交互和本地存储，最后给出交付报告。",
    },
    {
      role: "assistant",
      author: "Reviewer Agent",
      time: "14:24",
      content:
        "实现已覆盖核心验收标准。建议下一轮补充键盘快捷操作和空状态文案，当前版本可以作为稳定展示用例。",
    },
  ],
  tasks: [
    {
      id: "task-001",
      title: "需求整理与验收标准",
      description: "明确新增、完成、删除、搜索、本地存储和测试说明。",
      status: "completed",
      owner: "Planner",
      capabilities: ["tool.project_index"],
    },
    {
      id: "task-002",
      title: "实现 Todo 交互界面",
      description: "构建列表、输入框、过滤搜索和状态切换。",
      status: "completed",
      owner: "Coder",
      capabilities: ["tool.file_ops", "tool.project_index", "skill.frontend-polish"],
    },
    {
      id: "task-003",
      title: "接入本地存储",
      description: "使用 localStorage 保存任务数据和完成状态。",
      status: "completed",
      owner: "Coder",
      capabilities: ["tool.file_ops", "tool.project_index"],
    },
    {
      id: "task-004",
      title: "验证和交付报告",
      description: "检查核心流程并生成面向用户的交付摘要。",
      status: "in_progress",
      owner: "Tester",
      capabilities: ["skill.delivery-review", "tool.recovery"],
    },
  ],
  team: [
    {
      name: "Lead",
      role: "总控协调",
      status: "idle",
      initials: "L",
      tone: "lead",
      goal: "协调需求、任务、验证和交付报告。",
      tools: ["plan", "delegate", "report"],
      lastAction: "等待新的交付任务。",
      artifacts: ["report", "score"],
    },
    {
      name: "Planner",
      role: "需求拆解",
      status: "idle",
      initials: "P",
      tone: "planner",
      goal: "把用户需求拆成任务、依赖和验收点。",
      tools: ["task_create", "task_update"],
      lastAction: "维护任务板和需求覆盖。",
      artifacts: ["tasks", "requirements"],
    },
    {
      name: "Coder",
      role: "代码实现",
      status: "idle",
      initials: "C",
      tone: "coder",
      goal: "完成代码改动并保持 Diff 可审查。",
      tools: ["write_file", "edit_file", "bash"],
      lastAction: "准备处理文件变更。",
      artifacts: ["changed_files", "diff_patch"],
    },
    {
      name: "Tester",
      role: "验证交付",
      status: "running",
      initials: "T",
      tone: "tester",
      goal: "验证交付结果并暴露风险。",
      tools: ["bash", "manual_check"],
      lastAction: "检查核心验收路径。",
      artifacts: ["tests", "quality"],
    },
  ],
  events: [
    {
      type: "run_started",
      title: "任务已启动",
      content: "创建 nanoCursor 交付会话，并初始化任务板。",
      time: "14:20",
    },
    {
      type: "plan_created",
      title: "Planner 生成方案",
      content: "拆解为需求整理、界面实现、本地存储、验证报告四个任务。",
      time: "14:21",
    },
    {
      type: "tool_call_finished",
      title: "工具调用：write_file",
      content: "写入 src/App.tsx 和 src/styles.css。",
      time: "14:22",
    },
    {
      type: "tool_call_finished",
      title: "工具调用：bash",
      content: "执行前端构建检查，返回成功。",
      time: "14:23",
    },
    {
      type: "done",
      title: "交付报告已生成",
      content: "变更文件、验证结果和下一步建议已归档。",
      time: "14:24",
    },
  ],
  files: [
    { path: "demo-todo/index.html", type: "html", active: false },
    { path: "demo-todo/src/App.tsx", type: "tsx", active: true },
    { path: "demo-todo/src/styles.css", type: "css", active: false },
    { path: "demo-todo/package.json", type: "json", active: false },
    { path: "workspace/.nanocursor/runs/demo-run/report.md", type: "md", active: false },
  ],
  metrics: {
    tasks: 4,
    files: 4,
    toolCalls: 9,
    tokens: "12.8k",
    tests: "3/3",
  },
  capabilityHub: {
    summary: {
      total: 9,
      ready: 6,
      configured: 0,
      planned: 3,
    },
    groups: [
      {
        id: "tool",
        label: "内置工具",
        items: [
          {
            id: "tool.file_ops",
            name: "文件读写",
            kind: "tool",
            status: "ready",
            description: "读取、编辑、写入项目文件，并把变更沉淀到 Diff 与交付物。",
            tags: ["write_file", "edit_file", "diff"],
            agents: ["Coder", "Reviewer"],
          },
          {
            id: "tool.project_index",
            name: "项目索引",
            kind: "tool",
            status: "ready",
            description: "按符号、依赖、入口点理解代码库，减少盲目搜索。",
            tags: ["search_codebase", "project_context"],
            agents: ["Planner", "Coder"],
          },
          {
            id: "tool.memory",
            name: "偏好记忆",
            kind: "tool",
            status: "ready",
            description: "记录用户风格、技术栈和历史反馈，让 nanoCursor 越用越懂项目。",
            tags: ["add_memory", "recall_memories"],
            agents: ["Lead", "Planner"],
          },
          {
            id: "tool.recovery",
            name: "安全恢复",
            kind: "tool",
            status: "ready",
            description: "汇总备份、快照、风险，并支持受控文件回滚。",
            tags: ["snapshot", "rollback", "risk"],
            agents: ["Lead", "Tester"],
          },
        ],
      },
      {
        id: "mcp",
        label: "MCP 连接器",
        items: [
          {
            id: "mcp.github",
            name: "GitHub MCP",
            kind: "mcp",
            status: "planned",
            description: "接入 Issue、PR、代码审查和 CI 状态，形成真实研发协作闭环。",
            tags: ["issues", "pull_requests", "ci"],
            agents: ["Lead", "Reviewer"],
          },
          {
            id: "mcp.figma",
            name: "Figma MCP",
            kind: "mcp",
            status: "planned",
            description: "读取设计稿和组件规范，辅助 Designer / Coder 保持 UI 一致性。",
            tags: ["design", "components", "handoff"],
            agents: ["Designer", "Coder"],
          },
          {
            id: "mcp.docs",
            name: "文档知识库 MCP",
            kind: "mcp",
            status: "planned",
            description: "连接项目文档、接口说明和规范库，支持需求追踪与答疑。",
            tags: ["docs", "knowledge", "rag"],
            agents: ["Planner", "Tester"],
          },
        ],
      },
      {
        id: "skill",
        label: "Skills",
        items: [
          {
            id: "skill.frontend-polish",
            name: "前端体验打磨 Skill",
            kind: "skill",
            status: "ready",
            description: "沉淀浅色系、低拥挤、可折叠、按钮连续性的 UI 偏好。",
            tags: ["ui", "layout", "interaction"],
            agents: ["Designer", "Coder"],
            use_cases: ["浅色系工作台美化", "拥挤界面降噪", "折叠与响应式交互"],
            inputs: ["用户 UI 偏好", "当前页面结构", "截图反馈"],
            outputs: ["视觉改进建议", "前端样式补丁", "交互验收清单"],
            risks: ["可能影响已有布局密度，需要保留可扫描性。"],
          },
          {
            id: "skill.delivery-review",
            name: "交付复核 Skill",
            kind: "skill",
            status: "ready",
            description: "从需求覆盖、质量门禁、Diff 风险和恢复点复核一次交付。",
            tags: ["review", "quality", "traceability"],
            agents: ["Reviewer", "Tester"],
            use_cases: ["交付前验收", "风险复盘", "展示用例质量检查"],
            inputs: ["任务清单", "Diff 摘要", "测试结果", "交付报告"],
            outputs: ["覆盖率判断", "风险列表", "下一步修复建议"],
            risks: ["依赖输入证据完整度，缺少测试结果时只能给出部分结论。"],
          },
        ],
      },
    ],
  },
  capabilityRecommendation: {
    agents: ["Lead", "Planner", "Coder", "Tester"],
    capabilities: [],
    reasons: ["默认按完整软件交付流程推荐：先理解项目，再实现变更，最后复核质量。"],
    summary: {
      agent_count: 4,
      capability_count: 0,
      ready_count: 0,
      planned_count: 0,
    },
  },
  capabilityRecommendationDismissed: false,
  capabilityRecommendationMuted: sessionStorage.getItem(RECOMMENDATION_MUTED_KEY) === "1",
  showCompletedTasks: false,
  ephemeralAgents: {
    status: "idle",
    suggestions: [],
    agents: [],
    active_count: 0,
    archived_count: 0,
    total: 0,
    includeArchived: false,
    limits: {
      max_active_agents: 3,
      max_suggested_agents: 5,
    },
    mcp_plan_count: 0,
    error: "",
  },
  benchmarks: [
    {
      id: "todo-web-app",
      title: "Todo Web App",
      description: "交付支持新增、完成、删除、搜索和本地存储的前端小应用。",
      difficulty: "easy",
      category: "frontend",
      acceptance_criteria: ["create", "complete", "delete", "search", "localStorage"],
    },
    {
      id: "python-utils",
      title: "Python 工具函数补测试",
      description: "新增 slugify 工具函数并补充基础单元测试。",
      difficulty: "medium",
      category: "backend",
      acceptance_criteria: ["slugify spaces", "strip punctuation", "tests pass"],
    },
    {
      id: "bugfix-cart",
      title: "修复购物车数量 bug",
      description: "修复负数数量导致总价异常的问题，并补充回归测试。",
      difficulty: "medium",
      category: "bugfix",
      acceptance_criteria: ["reject negative quantity", "preserve total calculation", "regression test"],
    },
  ],
  previewUrl: "localhost:5173/demo-todo",
  selectedDiffFile: "",
  diffFiles: [],
  diff: `diff --git a/demo-todo/src/App.tsx b/demo-todo/src/App.tsx
new file mode 100644
--- /dev/null
+++ b/demo-todo/src/App.tsx
@@
+function TodoApp() {
+  const [items, setItems] = useLocalStorage("todos", []);
+  const [query, setQuery] = useState("");
+
+  const visibleItems = items.filter((item) =>
+    item.title.toLowerCase().includes(query.toLowerCase())
+  );
+
+  return (
+    <main className="todo-shell">
+      <TodoComposer onCreate={createItem} />
+      <TodoSearch value={query} onChange={setQuery} />
+      <TodoList items={visibleItems} onToggle={toggleItem} onDelete={deleteItem} />
+    </main>
+  );
+}`,
  report: {
    summary:
      "本次交付完成了一个支持新增、完成、删除、搜索和本地存储的 Todo Web App，并补充了手动测试说明。",
    markdown: "",
    requirements: [
      "支持创建任务并即时展示。",
      "支持完成状态切换和删除。",
      "支持按关键字搜索任务。",
      "刷新页面后保留任务数据。",
    ],
    changedFiles: [
      "demo-todo/src/App.tsx",
      "demo-todo/src/styles.css",
      "demo-todo/index.html",
      "demo-todo/package.json",
    ],
    risks: ["当前演示版本未接入自动化端到端测试。", "部署流程仍为本地预览，正式发布需要补充构建配置。"],
    traceability: {
      source: "demo",
      coverageRate: 1,
      totalCount: 4,
      coveredCount: 4,
      partialCount: 0,
      missingCount: 0,
      requirements: [
        {
          id: "REQ-001",
          title: "创建 Todo",
          status: "covered",
          tasks: ["task-002"],
          files: ["demo-todo/src/App.tsx"],
          tests: ["create"],
        },
        {
          id: "REQ-002",
          title: "完成和删除 Todo",
          status: "covered",
          tasks: ["task-002"],
          files: ["demo-todo/src/App.tsx"],
          tests: ["complete", "delete"],
        },
        {
          id: "REQ-003",
          title: "搜索 Todo",
          status: "covered",
          tasks: ["task-002"],
          files: ["demo-todo/src/App.tsx"],
          tests: ["search"],
        },
        {
          id: "REQ-004",
          title: "本地持久化",
          status: "covered",
          tasks: ["task-003"],
          files: ["demo-todo/src/App.tsx"],
          tests: ["localStorage"],
        },
      ],
    },
  },
  artifactCenter: {
    status: "ready",
    summary: {
      artifact_count: 9,
      ready_count: 8,
      warning_count: 1,
      missing_count: 0,
      score: 92,
      coverage_rate: 1,
    },
    artifacts: [
      {
        id: "requirements",
        kind: "requirements",
        label: "需求摘要",
        status: "ready",
        summary: "4 / 4 个需求已覆盖",
        count: 4,
      },
      {
        id: "tasks",
        kind: "tasks",
        label: "任务清单",
        status: "warning",
        summary: "3 / 4 个任务已完成",
        count: 4,
      },
      {
        id: "changed_files",
        kind: "files",
        label: "变更文件",
        status: "ready",
        summary: "4 个文件发生变化",
        count: 4,
      },
      {
        id: "diff_patch",
        kind: "diff",
        label: "Diff Patch",
        status: "ready",
        summary: "Diff 来源：demo",
      },
      {
        id: "report",
        kind: "report",
        label: "交付报告",
        status: "ready",
        summary: "已生成面向评审的交付摘要",
      },
    ],
  },
  memoryProfile: {
    total_memories: 3,
    preference_count: 3,
    high_importance_count: 2,
    prompt_context:
      "代码风格:\n- 偏好小步提交、清晰命名和必要注释。\nUI 风格:\n- 偏好克制、专业、信息密度高的工作台界面。",
    buckets: [
      {
        id: "code_style",
        label: "代码风格",
        description: "命名、注释、类型、格式化和代码组织习惯。",
        confidence: "high",
        memories: [{ id: "demo-code", content: "偏好小步提交、清晰命名和必要注释。", importance: 8, tags: [] }],
      },
      {
        id: "ui_style",
        label: "UI 风格",
        description: "界面审美、布局密度、颜色、交互和组件偏好。",
        confidence: "high",
        memories: [{ id: "demo-ui", content: "偏好克制、专业、信息密度高的工作台界面。", importance: 8, tags: [] }],
      },
      {
        id: "testing",
        label: "测试偏好",
        description: "单元测试、端到端测试、验证策略和质量门禁习惯。",
        confidence: "medium",
        memories: [{ id: "demo-test", content: "后端功能需要补充可重复运行的 pytest。", importance: 6, tags: [] }],
      },
    ],
  },
  recoveryCenter: {
    status: "safe",
    summary: {
      snapshot_count: 1,
      backup_count: 3,
      risk_count: 0,
      high_risk_count: 0,
      has_recovery_points: true,
    },
    recovery_points: [
      {
        id: "demo-snapshot",
        kind: "snapshot",
        label: "执行前快照",
        status: "available",
        reason: "before_demo_run",
        detail: "捕获 Demo Run 前的工作区状态。",
      },
      {
        id: "demo-todo_app.js.bak",
        kind: "backup",
        label: "demo-todo_app.js.bak",
        status: "available",
        target_path: "demo-todo/app.js",
        size: 2048,
        detail: "文件备份可用于指定路径回滚。",
      },
    ],
    risks: [],
  },
  mcpConfig: {
    servers: [],
    presets: [],
    config_paths: [],
    summary: {},
    presetSummary: {},
    validation: null,
    validationByServer: {},
    statusByServer: {},
    toolsByServer: {},
  },
  skillDetail: null,
  skillEditing: false,
  workspaceSettings: null,
  recentProjects: [],
};
