// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/filetools.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_proto_filetools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{0}
}

func (x *ReadFileRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ReadFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_proto_filetools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{1}
}

func (x *ReadFileResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ReadFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	FunctionName  string                 `protobuf:"bytes,3,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFunctionRequest) Reset() {
	*x = ReadFunctionRequest{}
	mi := &file_proto_filetools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFunctionRequest) ProtoMessage() {}

func (x *ReadFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFunctionRequest.ProtoReflect.Descriptor instead.
func (*ReadFunctionRequest) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{2}
}

func (x *ReadFunctionRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ReadFunctionRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ReadFunctionRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

type ReadFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFunctionResponse) Reset() {
	*x = ReadFunctionResponse{}
	mi := &file_proto_filetools_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFunctionResponse) ProtoMessage() {}

func (x *ReadFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFunctionResponse.ProtoReflect.Descriptor instead.
func (*ReadFunctionResponse) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{3}
}

func (x *ReadFunctionResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ReadClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ClassName     string                 `protobuf:"bytes,3,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadClassRequest) Reset() {
	*x = ReadClassRequest{}
	mi := &file_proto_filetools_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadClassRequest) ProtoMessage() {}

func (x *ReadClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadClassRequest.ProtoReflect.Descriptor instead.
func (*ReadClassRequest) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{4}
}

func (x *ReadClassRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ReadClassRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ReadClassRequest) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type ReadClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadClassResponse) Reset() {
	*x = ReadClassResponse{}
	mi := &file_proto_filetools_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadClassResponse) ProtoMessage() {}

func (x *ReadClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadClassResponse.ProtoReflect.Descriptor instead.
func (*ReadClassResponse) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{5}
}

func (x *ReadClassResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ReadFileRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	StartLine     int32                  `protobuf:"varint,3,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	EndLine       int32                  `protobuf:"varint,4,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRangeRequest) Reset() {
	*x = ReadFileRangeRequest{}
	mi := &file_proto_filetools_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRangeRequest) ProtoMessage() {}

func (x *ReadFileRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRangeRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{6}
}

func (x *ReadFileRangeRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ReadFileRangeRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ReadFileRangeRequest) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *ReadFileRangeRequest) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

type ReadFileRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRangeResponse) Reset() {
	*x = ReadFileRangeResponse{}
	mi := &file_proto_filetools_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRangeResponse) ProtoMessage() {}

func (x *ReadFileRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRangeResponse.ProtoReflect.Descriptor instead.
func (*ReadFileRangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{7}
}

func (x *ReadFileRangeResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ListDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryRequest) Reset() {
	*x = ListDirectoryRequest{}
	mi := &file_proto_filetools_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryRequest) ProtoMessage() {}

func (x *ListDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryRequest.ProtoReflect.Descriptor instead.
func (*ListDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{8}
}

func (x *ListDirectoryRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ListDirectoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryResponse) Reset() {
	*x = ListDirectoryResponse{}
	mi := &file_proto_filetools_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryResponse) ProtoMessage() {}

func (x *ListDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryResponse.ProtoReflect.Descriptor instead.
func (*ListDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{9}
}

func (x *ListDirectoryResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type WriteFileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Workspace      string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Filename       string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Overwrite      bool                   `protobuf:"varint,4,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	BackupExisting bool                   `protobuf:"varint,5,opt,name=backup_existing,json=backupExisting,proto3" json:"backup_existing,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_proto_filetools_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{10}
}

func (x *WriteFileRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *WriteFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *WriteFileRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WriteFileRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

func (x *WriteFileRequest) GetBackupExisting() bool {
	if x != nil {
		return x.BackupExisting
	}
	return false
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_proto_filetools_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{11}
}

func (x *WriteFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EditFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	SearchBlock   string                 `protobuf:"bytes,3,opt,name=search_block,json=searchBlock,proto3" json:"search_block,omitempty"`
	ReplaceBlock  string                 `protobuf:"bytes,4,opt,name=replace_block,json=replaceBlock,proto3" json:"replace_block,omitempty"`
	StartLine     int32                  `protobuf:"varint,5,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	EndLine       int32                  `protobuf:"varint,6,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	NewText       string                 `protobuf:"bytes,7,opt,name=new_text,json=newText,proto3" json:"new_text,omitempty"`
	CreateBackup  bool                   `protobuf:"varint,9,opt,name=create_backup,json=createBackup,proto3" json:"create_backup,omitempty"`
	MatchMode     string                 `protobuf:"bytes,10,opt,name=match_mode,json=matchMode,proto3" json:"match_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditFileRequest) Reset() {
	*x = EditFileRequest{}
	mi := &file_proto_filetools_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditFileRequest) ProtoMessage() {}

func (x *EditFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditFileRequest.ProtoReflect.Descriptor instead.
func (*EditFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{12}
}

func (x *EditFileRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *EditFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *EditFileRequest) GetSearchBlock() string {
	if x != nil {
		return x.SearchBlock
	}
	return ""
}

func (x *EditFileRequest) GetReplaceBlock() string {
	if x != nil {
		return x.ReplaceBlock
	}
	return ""
}

func (x *EditFileRequest) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *EditFileRequest) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *EditFileRequest) GetNewText() string {
	if x != nil {
		return x.NewText
	}
	return ""
}

func (x *EditFileRequest) GetCreateBackup() bool {
	if x != nil {
		return x.CreateBackup
	}
	return false
}

func (x *EditFileRequest) GetMatchMode() string {
	if x != nil {
		return x.MatchMode
	}
	return ""
}

type EditFileResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Result           string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Diff             string                 `protobuf:"bytes,2,opt,name=diff,proto3" json:"diff,omitempty"`
	Strategy         string                 `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	MatchedStartLine int32                  `protobuf:"varint,4,opt,name=matched_start_line,json=matchedStartLine,proto3" json:"matched_start_line,omitempty"`
	MatchedEndLine   int32                  `protobuf:"varint,5,opt,name=matched_end_line,json=matchedEndLine,proto3" json:"matched_end_line,omitempty"`
	ChangedLineCount int32                  `protobuf:"varint,6,opt,name=changed_line_count,json=changedLineCount,proto3" json:"changed_line_count,omitempty"`
	BackupPath       string                 `protobuf:"bytes,7,opt,name=backup_path,json=backupPath,proto3" json:"backup_path,omitempty"`
	Changed          bool                   `protobuf:"varint,8,opt,name=changed,proto3" json:"changed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EditFileResponse) Reset() {
	*x = EditFileResponse{}
	mi := &file_proto_filetools_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditFileResponse) ProtoMessage() {}

func (x *EditFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditFileResponse.ProtoReflect.Descriptor instead.
func (*EditFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{13}
}

func (x *EditFileResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *EditFileResponse) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

func (x *EditFileResponse) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *EditFileResponse) GetMatchedStartLine() int32 {
	if x != nil {
		return x.MatchedStartLine
	}
	return 0
}

func (x *EditFileResponse) GetMatchedEndLine() int32 {
	if x != nil {
		return x.MatchedEndLine
	}
	return 0
}

func (x *EditFileResponse) GetChangedLineCount() int32 {
	if x != nil {
		return x.ChangedLineCount
	}
	return 0
}

func (x *EditFileResponse) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

func (x *EditFileResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

type BackupFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupFileRequest) Reset() {
	*x = BackupFileRequest{}
	mi := &file_proto_filetools_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupFileRequest) ProtoMessage() {}

func (x *BackupFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupFileRequest.ProtoReflect.Descriptor instead.
func (*BackupFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{14}
}

func (x *BackupFileRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *BackupFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type BackupFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupPath    string                 `protobuf:"bytes,1,opt,name=backup_path,json=backupPath,proto3" json:"backup_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupFileResponse) Reset() {
	*x = BackupFileResponse{}
	mi := &file_proto_filetools_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupFileResponse) ProtoMessage() {}

func (x *BackupFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupFileResponse.ProtoReflect.Descriptor instead.
func (*BackupFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{15}
}

func (x *BackupFileResponse) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

type RollbackFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	BackupIndex   int32                  `protobuf:"varint,3,opt,name=backup_index,json=backupIndex,proto3" json:"backup_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackFileRequest) Reset() {
	*x = RollbackFileRequest{}
	mi := &file_proto_filetools_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackFileRequest) ProtoMessage() {}

func (x *RollbackFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackFileRequest.ProtoReflect.Descriptor instead.
func (*RollbackFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{16}
}

func (x *RollbackFileRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *RollbackFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *RollbackFileRequest) GetBackupIndex() int32 {
	if x != nil {
		return x.BackupIndex
	}
	return 0
}

type RollbackFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackFileResponse) Reset() {
	*x = RollbackFileResponse{}
	mi := &file_proto_filetools_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackFileResponse) ProtoMessage() {}

func (x *RollbackFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackFileResponse.ProtoReflect.Descriptor instead.
func (*RollbackFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{17}
}

func (x *RollbackFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListBackupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsRequest) Reset() {
	*x = ListBackupsRequest{}
	mi := &file_proto_filetools_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsRequest) ProtoMessage() {}

func (x *ListBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsRequest.ProtoReflect.Descriptor instead.
func (*ListBackupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{18}
}

func (x *ListBackupsRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ListBackupsRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ListBackupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsResponse) Reset() {
	*x = ListBackupsResponse{}
	mi := &file_proto_filetools_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsResponse) ProtoMessage() {}

func (x *ListBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsResponse.ProtoReflect.Descriptor instead.
func (*ListBackupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{19}
}

func (x *ListBackupsResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_filetools_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{20}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_filetools_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetools_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_filetools_proto_rawDescGZIP(), []int{21}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_filetools_proto protoreflect.FileDescriptor

const file_proto_filetools_proto_rawDesc = "" +
	"\n" +
	"\x15proto/filetools.proto\x12\x14nanocursor.filetools\"K\n" +
	"\x0fReadFileRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\",\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"t\n" +
	"\x13ReadFunctionRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12#\n" +
	"\rfunction_name\x18\x03 \x01(\tR\ffunctionName\"0\n" +
	"\x14ReadFunctionResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"k\n" +
	"\x10ReadClassRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"class_name\x18\x03 \x01(\tR\tclassName\"-\n" +
	"\x11ReadClassResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\x8a\x01\n" +
	"\x14ReadFileRangeRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"start_line\x18\x03 \x01(\x05R\tstartLine\x12\x19\n" +
	"\bend_line\x18\x04 \x01(\x05R\aendLine\"1\n" +
	"\x15ReadFileRangeResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"H\n" +
	"\x14ListDirectoryRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"1\n" +
	"\x15ListDirectoryResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\xad\x01\n" +
	"\x10WriteFileRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\toverwrite\x18\x04 \x01(\bR\toverwrite\x12'\n" +
	"\x0fbackup_existing\x18\x05 \x01(\bR\x0ebackupExisting\"-\n" +
	"\x11WriteFileResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xb2\x02\n" +
	"\x0fEditFileRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fsearch_block\x18\x03 \x01(\tR\vsearchBlock\x12#\n" +
	"\rreplace_block\x18\x04 \x01(\tR\freplaceBlock\x12\x1d\n" +
	"\n" +
	"start_line\x18\x05 \x01(\x05R\tstartLine\x12\x19\n" +
	"\bend_line\x18\x06 \x01(\x05R\aendLine\x12\x19\n" +
	"\bnew_text\x18\a \x01(\tR\anewText\x12#\n" +
	"\rcreate_backup\x18\t \x01(\bR\fcreateBackup\x12\x1d\n" +
	"\n" +
	"match_mode\x18\n" +
	" \x01(\tR\tmatchModeJ\x04\b\b\x10\t\"\x9b\x02\n" +
	"\x10EditFileResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x12\n" +
	"\x04diff\x18\x02 \x01(\tR\x04diff\x12\x1a\n" +
	"\bstrategy\x18\x03 \x01(\tR\bstrategy\x12,\n" +
	"\x12matched_start_line\x18\x04 \x01(\x05R\x10matchedStartLine\x12(\n" +
	"\x10matched_end_line\x18\x05 \x01(\x05R\x0ematchedEndLine\x12,\n" +
	"\x12changed_line_count\x18\x06 \x01(\x05R\x10changedLineCount\x12\x1f\n" +
	"\vbackup_path\x18\a \x01(\tR\n" +
	"backupPath\x12\x18\n" +
	"\achanged\x18\b \x01(\bR\achanged\"M\n" +
	"\x11BackupFileRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"5\n" +
	"\x12BackupFileResponse\x12\x1f\n" +
	"\vbackup_path\x18\x01 \x01(\tR\n" +
	"backupPath\"r\n" +
	"\x13RollbackFileRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fbackup_index\x18\x03 \x01(\x05R\vbackupIndex\"0\n" +
	"\x14RollbackFileResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"N\n" +
	"\x12ListBackupsRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"/\n" +
	"\x13ListBackupsResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\x0f\n" +
	"\rHealthRequest\"T\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion2\xb9\b\n" +
	"\tFileTools\x12Y\n" +
	"\bReadFile\x12%.nanocursor.filetools.ReadFileRequest\x1a&.nanocursor.filetools.ReadFileResponse\x12e\n" +
	"\fReadFunction\x12).nanocursor.filetools.ReadFunctionRequest\x1a*.nanocursor.filetools.ReadFunctionResponse\x12\\\n" +
	"\tReadClass\x12&.nanocursor.filetools.ReadClassRequest\x1a'.nanocursor.filetools.ReadClassResponse\x12h\n" +
	"\rReadFileRange\x12*.nanocursor.filetools.ReadFileRangeRequest\x1a+.nanocursor.filetools.ReadFileRangeResponse\x12h\n" +
	"\rListDirectory\x12*.nanocursor.filetools.ListDirectoryRequest\x1a+.nanocursor.filetools.ListDirectoryResponse\x12\\\n" +
	"\tWriteFile\x12&.nanocursor.filetools.WriteFileRequest\x1a'.nanocursor.filetools.WriteFileResponse\x12Y\n" +
	"\bEditFile\x12%.nanocursor.filetools.EditFileRequest\x1a&.nanocursor.filetools.EditFileResponse\x12_\n" +
	"\n" +
	"BackupFile\x12'.nanocursor.filetools.BackupFileRequest\x1a(.nanocursor.filetools.BackupFileResponse\x12e\n" +
	"\fRollbackFile\x12).nanocursor.filetools.RollbackFileRequest\x1a*.nanocursor.filetools.RollbackFileResponse\x12b\n" +
	"\vListBackups\x12(.nanocursor.filetools.ListBackupsRequest\x1a).nanocursor.filetools.ListBackupsResponse\x12S\n" +
	"\x06Health\x12#.nanocursor.filetools.HealthRequest\x1a$.nanocursor.filetools.HealthResponseB2Z0nanocursor/go-services/filetools/internal/serverb\x06proto3"

var (
	file_proto_filetools_proto_rawDescOnce sync.Once
	file_proto_filetools_proto_rawDescData []byte
)

func file_proto_filetools_proto_rawDescGZIP() []byte {
	file_proto_filetools_proto_rawDescOnce.Do(func() {
		file_proto_filetools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_filetools_proto_rawDesc), len(file_proto_filetools_proto_rawDesc)))
	})
	return file_proto_filetools_proto_rawDescData
}

var file_proto_filetools_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_filetools_proto_goTypes = []any{
	(*ReadFileRequest)(nil),       // 0: nanocursor.filetools.ReadFileRequest
	(*ReadFileResponse)(nil),      // 1: nanocursor.filetools.ReadFileResponse
	(*ReadFunctionRequest)(nil),   // 2: nanocursor.filetools.ReadFunctionRequest
	(*ReadFunctionResponse)(nil),  // 3: nanocursor.filetools.ReadFunctionResponse
	(*ReadClassRequest)(nil),      // 4: nanocursor.filetools.ReadClassRequest
	(*ReadClassResponse)(nil),     // 5: nanocursor.filetools.ReadClassResponse
	(*ReadFileRangeRequest)(nil),  // 6: nanocursor.filetools.ReadFileRangeRequest
	(*ReadFileRangeResponse)(nil), // 7: nanocursor.filetools.ReadFileRangeResponse
	(*ListDirectoryRequest)(nil),  // 8: nanocursor.filetools.ListDirectoryRequest
	(*ListDirectoryResponse)(nil), // 9: nanocursor.filetools.ListDirectoryResponse
	(*WriteFileRequest)(nil),      // 10: nanocursor.filetools.WriteFileRequest
	(*WriteFileResponse)(nil),     // 11: nanocursor.filetools.WriteFileResponse
	(*EditFileRequest)(nil),       // 12: nanocursor.filetools.EditFileRequest
	(*EditFileResponse)(nil),      // 13: nanocursor.filetools.EditFileResponse
	(*BackupFileRequest)(nil),     // 14: nanocursor.filetools.BackupFileRequest
	(*BackupFileResponse)(nil),    // 15: nanocursor.filetools.BackupFileResponse
	(*RollbackFileRequest)(nil),   // 16: nanocursor.filetools.RollbackFileRequest
	(*RollbackFileResponse)(nil),  // 17: nanocursor.filetools.RollbackFileResponse
	(*ListBackupsRequest)(nil),    // 18: nanocursor.filetools.ListBackupsRequest
	(*ListBackupsResponse)(nil),   // 19: nanocursor.filetools.ListBackupsResponse
	(*HealthRequest)(nil),         // 20: nanocursor.filetools.HealthRequest
	(*HealthResponse)(nil),        // 21: nanocursor.filetools.HealthResponse
}
var file_proto_filetools_proto_depIdxs = []int32{
	0,  // 0: nanocursor.filetools.FileTools.ReadFile:input_type -> nanocursor.filetools.ReadFileRequest
	2,  // 1: nanocursor.filetools.FileTools.ReadFunction:input_type -> nanocursor.filetools.ReadFunctionRequest
	4,  // 2: nanocursor.filetools.FileTools.ReadClass:input_type -> nanocursor.filetools.ReadClassRequest
	6,  // 3: nanocursor.filetools.FileTools.ReadFileRange:input_type -> nanocursor.filetools.ReadFileRangeRequest
	8,  // 4: nanocursor.filetools.FileTools.ListDirectory:input_type -> nanocursor.filetools.ListDirectoryRequest
	10, // 5: nanocursor.filetools.FileTools.WriteFile:input_type -> nanocursor.filetools.WriteFileRequest
	12, // 6: nanocursor.filetools.FileTools.EditFile:input_type -> nanocursor.filetools.EditFileRequest
	14, // 7: nanocursor.filetools.FileTools.BackupFile:input_type -> nanocursor.filetools.BackupFileRequest
	16, // 8: nanocursor.filetools.FileTools.RollbackFile:input_type -> nanocursor.filetools.RollbackFileRequest
	18, // 9: nanocursor.filetools.FileTools.ListBackups:input_type -> nanocursor.filetools.ListBackupsRequest
	20, // 10: nanocursor.filetools.FileTools.Health:input_type -> nanocursor.filetools.HealthRequest
	1,  // 11: nanocursor.filetools.FileTools.ReadFile:output_type -> nanocursor.filetools.ReadFileResponse
	3,  // 12: nanocursor.filetools.FileTools.ReadFunction:output_type -> nanocursor.filetools.ReadFunctionResponse
	5,  // 13: nanocursor.filetools.FileTools.ReadClass:output_type -> nanocursor.filetools.ReadClassResponse
	7,  // 14: nanocursor.filetools.FileTools.ReadFileRange:output_type -> nanocursor.filetools.ReadFileRangeResponse
	9,  // 15: nanocursor.filetools.FileTools.ListDirectory:output_type -> nanocursor.filetools.ListDirectoryResponse
	11, // 16: nanocursor.filetools.FileTools.WriteFile:output_type -> nanocursor.filetools.WriteFileResponse
	13, // 17: nanocursor.filetools.FileTools.EditFile:output_type -> nanocursor.filetools.EditFileResponse
	15, // 18: nanocursor.filetools.FileTools.BackupFile:output_type -> nanocursor.filetools.BackupFileResponse
	17, // 19: nanocursor.filetools.FileTools.RollbackFile:output_type -> nanocursor.filetools.RollbackFileResponse
	19, // 20: nanocursor.filetools.FileTools.ListBackups:output_type -> nanocursor.filetools.ListBackupsResponse
	21, // 21: nanocursor.filetools.FileTools.Health:output_type -> nanocursor.filetools.HealthResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_filetools_proto_init() }
func file_proto_filetools_proto_init() {
	if File_proto_filetools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_filetools_proto_rawDesc), len(file_proto_filetools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_filetools_proto_goTypes,
		DependencyIndexes: file_proto_filetools_proto_depIdxs,
		MessageInfos:      file_proto_filetools_proto_msgTypes,
	}.Build()
	File_proto_filetools_proto = out.File
	file_proto_filetools_proto_goTypes = nil
	file_proto_filetools_proto_depIdxs = nil
}
