// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/filetools.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileTools_ReadFile_FullMethodName      = "/nanocursor.filetools.FileTools/ReadFile"
	FileTools_ReadFunction_FullMethodName  = "/nanocursor.filetools.FileTools/ReadFunction"
	FileTools_ReadClass_FullMethodName     = "/nanocursor.filetools.FileTools/ReadClass"
	FileTools_ReadFileRange_FullMethodName = "/nanocursor.filetools.FileTools/ReadFileRange"
	FileTools_ListDirectory_FullMethodName = "/nanocursor.filetools.FileTools/ListDirectory"
	FileTools_WriteFile_FullMethodName     = "/nanocursor.filetools.FileTools/WriteFile"
	FileTools_EditFile_FullMethodName      = "/nanocursor.filetools.FileTools/EditFile"
	FileTools_BackupFile_FullMethodName    = "/nanocursor.filetools.FileTools/BackupFile"
	FileTools_RollbackFile_FullMethodName  = "/nanocursor.filetools.FileTools/RollbackFile"
	FileTools_ListBackups_FullMethodName   = "/nanocursor.filetools.FileTools/ListBackups"
	FileTools_Health_FullMethodName        = "/nanocursor.filetools.FileTools/Health"
)

// FileToolsClient is the client API for FileTools service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileToolsClient interface {
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	ReadFunction(ctx context.Context, in *ReadFunctionRequest, opts ...grpc.CallOption) (*ReadFunctionResponse, error)
	ReadClass(ctx context.Context, in *ReadClassRequest, opts ...grpc.CallOption) (*ReadClassResponse, error)
	ReadFileRange(ctx context.Context, in *ReadFileRangeRequest, opts ...grpc.CallOption) (*ReadFileRangeResponse, error)
	ListDirectory(ctx context.Context, in *ListDirectoryRequest, opts ...grpc.CallOption) (*ListDirectoryResponse, error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	EditFile(ctx context.Context, in *EditFileRequest, opts ...grpc.CallOption) (*EditFileResponse, error)
	BackupFile(ctx context.Context, in *BackupFileRequest, opts ...grpc.CallOption) (*BackupFileResponse, error)
	RollbackFile(ctx context.Context, in *RollbackFileRequest, opts ...grpc.CallOption) (*RollbackFileResponse, error)
	ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type fileToolsClient struct {
	cc grpc.ClientConnInterface
}

func NewFileToolsClient(cc grpc.ClientConnInterface) FileToolsClient {
	return &fileToolsClient{cc}
}

func (c *fileToolsClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, FileTools_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileToolsClient) ReadFunction(ctx context.Context, in *ReadFunctionRequest, opts ...grpc.CallOption) (*ReadFunctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFunctionResponse)
	err := c.cc.Invoke(ctx, FileTools_ReadFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileToolsClient) ReadClass(ctx context.Context, in *ReadClassRequest, opts ...grpc.CallOption) (*ReadClassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadClassResponse)
	err := c.cc.Invoke(ctx, FileTools_ReadClass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileToolsClient) ReadFileRange(ctx context.Context, in *ReadFileRangeRequest, opts ...grpc.CallOption) (*ReadFileRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileRangeResponse)
	err := c.cc.Invoke(ctx, FileTools_ReadFileRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileToolsClient) ListDirectory(ctx context.Context, in *ListDirectoryRequest, opts ...grpc.CallOption) (*ListDirectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirectoryResponse)
	err := c.cc.Invoke(ctx, FileTools_ListDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileToolsClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, FileTools_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileToolsClient) EditFile(ctx context.Context, in *EditFileRequest, opts ...grpc.CallOption) (*EditFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditFileResponse)
	err := c.cc.Invoke(ctx, FileTools_EditFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileToolsClient) BackupFile(ctx context.Context, in *BackupFileRequest, opts ...grpc.CallOption) (*BackupFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupFileResponse)
	err := c.cc.Invoke(ctx, FileTools_BackupFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileToolsClient) RollbackFile(ctx context.Context, in *RollbackFileRequest, opts ...grpc.CallOption) (*RollbackFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackFileResponse)
	err := c.cc.Invoke(ctx, FileTools_RollbackFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileToolsClient) ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBackupsResponse)
	err := c.cc.Invoke(ctx, FileTools_ListBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileToolsClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, FileTools_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileToolsServer is the server API for FileTools service.
// All implementations must embed UnimplementedFileToolsServer
// for forward compatibility.
type FileToolsServer interface {
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	ReadFunction(context.Context, *ReadFunctionRequest) (*ReadFunctionResponse, error)
	ReadClass(context.Context, *ReadClassRequest) (*ReadClassResponse, error)
	ReadFileRange(context.Context, *ReadFileRangeRequest) (*ReadFileRangeResponse, error)
	ListDirectory(context.Context, *ListDirectoryRequest) (*ListDirectoryResponse, error)
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	EditFile(context.Context, *EditFileRequest) (*EditFileResponse, error)
	BackupFile(context.Context, *BackupFileRequest) (*BackupFileResponse, error)
	RollbackFile(context.Context, *RollbackFileRequest) (*RollbackFileResponse, error)
	ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedFileToolsServer()
}

// UnimplementedFileToolsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileToolsServer struct{}

func (UnimplementedFileToolsServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedFileToolsServer) ReadFunction(context.Context, *ReadFunctionRequest) (*ReadFunctionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFunction not implemented")
}
func (UnimplementedFileToolsServer) ReadClass(context.Context, *ReadClassRequest) (*ReadClassResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadClass not implemented")
}
func (UnimplementedFileToolsServer) ReadFileRange(context.Context, *ReadFileRangeRequest) (*ReadFileRangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFileRange not implemented")
}
func (UnimplementedFileToolsServer) ListDirectory(context.Context, *ListDirectoryRequest) (*ListDirectoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDirectory not implemented")
}
func (UnimplementedFileToolsServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedFileToolsServer) EditFile(context.Context, *EditFileRequest) (*EditFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditFile not implemented")
}
func (UnimplementedFileToolsServer) BackupFile(context.Context, *BackupFileRequest) (*BackupFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BackupFile not implemented")
}
func (UnimplementedFileToolsServer) RollbackFile(context.Context, *RollbackFileRequest) (*RollbackFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackFile not implemented")
}
func (UnimplementedFileToolsServer) ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBackups not implemented")
}
func (UnimplementedFileToolsServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedFileToolsServer) mustEmbedUnimplementedFileToolsServer() {}
func (UnimplementedFileToolsServer) testEmbeddedByValue()                   {}

// UnsafeFileToolsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileToolsServer will
// result in compilation errors.
type UnsafeFileToolsServer interface {
	mustEmbedUnimplementedFileToolsServer()
}

func RegisterFileToolsServer(s grpc.ServiceRegistrar, srv FileToolsServer) {
	// If the following call panics, it indicates UnimplementedFileToolsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileTools_ServiceDesc, srv)
}

func _FileTools_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileToolsServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileTools_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileToolsServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTools_ReadFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileToolsServer).ReadFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileTools_ReadFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileToolsServer).ReadFunction(ctx, req.(*ReadFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTools_ReadClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileToolsServer).ReadClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileTools_ReadClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileToolsServer).ReadClass(ctx, req.(*ReadClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTools_ReadFileRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileToolsServer).ReadFileRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileTools_ReadFileRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileToolsServer).ReadFileRange(ctx, req.(*ReadFileRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTools_ListDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileToolsServer).ListDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileTools_ListDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileToolsServer).ListDirectory(ctx, req.(*ListDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTools_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileToolsServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileTools_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileToolsServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTools_EditFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileToolsServer).EditFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileTools_EditFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileToolsServer).EditFile(ctx, req.(*EditFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTools_BackupFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileToolsServer).BackupFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileTools_BackupFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileToolsServer).BackupFile(ctx, req.(*BackupFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTools_RollbackFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileToolsServer).RollbackFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileTools_RollbackFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileToolsServer).RollbackFile(ctx, req.(*RollbackFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTools_ListBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileToolsServer).ListBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileTools_ListBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileToolsServer).ListBackups(ctx, req.(*ListBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTools_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileToolsServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileTools_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileToolsServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileTools_ServiceDesc is the grpc.ServiceDesc for FileTools service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileTools_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanocursor.filetools.FileTools",
	HandlerType: (*FileToolsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadFile",
			Handler:    _FileTools_ReadFile_Handler,
		},
		{
			MethodName: "ReadFunction",
			Handler:    _FileTools_ReadFunction_Handler,
		},
		{
			MethodName: "ReadClass",
			Handler:    _FileTools_ReadClass_Handler,
		},
		{
			MethodName: "ReadFileRange",
			Handler:    _FileTools_ReadFileRange_Handler,
		},
		{
			MethodName: "ListDirectory",
			Handler:    _FileTools_ListDirectory_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _FileTools_WriteFile_Handler,
		},
		{
			MethodName: "EditFile",
			Handler:    _FileTools_EditFile_Handler,
		},
		{
			MethodName: "BackupFile",
			Handler:    _FileTools_BackupFile_Handler,
		},
		{
			MethodName: "RollbackFile",
			Handler:    _FileTools_RollbackFile_Handler,
		},
		{
			MethodName: "ListBackups",
			Handler:    _FileTools_ListBackups_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _FileTools_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/filetools.proto",
}
