// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/mcp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPresetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPresetsRequest) Reset() {
	*x = ListPresetsRequest{}
	mi := &file_proto_mcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPresetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPresetsRequest) ProtoMessage() {}

func (x *ListPresetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPresetsRequest.ProtoReflect.Descriptor instead.
func (*ListPresetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{0}
}

type PresetList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presets       []*Preset              `protobuf:"bytes,1,rep,name=presets,proto3" json:"presets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresetList) Reset() {
	*x = PresetList{}
	mi := &file_proto_mcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresetList) ProtoMessage() {}

func (x *PresetList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresetList.ProtoReflect.Descriptor instead.
func (*PresetList) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{1}
}

func (x *PresetList) GetPresets() []*Preset {
	if x != nil {
		return x.Presets
	}
	return nil
}

type Preset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Preset) Reset() {
	*x = Preset{}
	mi := &file_proto_mcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preset) ProtoMessage() {}

func (x *Preset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preset.ProtoReflect.Descriptor instead.
func (*Preset) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{2}
}

func (x *Preset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Preset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Preset) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Preset) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Preset) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Preset) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type ListServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersRequest) Reset() {
	*x = ListServersRequest{}
	mi := &file_proto_mcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersRequest) ProtoMessage() {}

func (x *ListServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersRequest.ProtoReflect.Descriptor instead.
func (*ListServersRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{3}
}

type ServerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*Server              `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerList) Reset() {
	*x = ServerList{}
	mi := &file_proto_mcp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerList) ProtoMessage() {}

func (x *ServerList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerList.ProtoReflect.Descriptor instead.
func (*ServerList) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{4}
}

func (x *ServerList) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_proto_mcp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{5}
}

func (x *Server) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Server) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Server) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Server) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	WorkspaceDir  string                 `protobuf:"bytes,2,opt,name=workspace_dir,json=workspaceDir,proto3" json:"workspace_dir,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EnvKeys       []string               `protobuf:"bytes,6,rep,name=env_keys,json=envKeys,proto3" json:"env_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	mi := &file_proto_mcp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{6}
}

func (x *ProbeRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ProbeRequest) GetWorkspaceDir() string {
	if x != nil {
		return x.WorkspaceDir
	}
	return ""
}

func (x *ProbeRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ProbeRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ProbeRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ProbeRequest) GetEnvKeys() []string {
	if x != nil {
		return x.EnvKeys
	}
	return nil
}

type ProbeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResult) Reset() {
	*x = ProbeResult{}
	mi := &file_proto_mcp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResult) ProtoMessage() {}

func (x *ProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResult.ProtoReflect.Descriptor instead.
func (*ProbeResult) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{7}
}

func (x *ProbeResult) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ProbeResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProbeResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ProbeResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_proto_mcp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{8}
}

func (x *ListToolsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type ToolList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*MCPTool             `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolList) Reset() {
	*x = ToolList{}
	mi := &file_proto_mcp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolList) ProtoMessage() {}

func (x *ToolList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolList.ProtoReflect.Descriptor instead.
func (*ToolList) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{9}
}

func (x *ToolList) GetTools() []*MCPTool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ToolList) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ToolList) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ToolList) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MCPTool struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputSchema      string                 `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	PermissionLevel  string                 `protobuf:"bytes,4,opt,name=permission_level,json=permissionLevel,proto3" json:"permission_level,omitempty"`
	RequiresApproval bool                   `protobuf:"varint,5,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MCPTool) Reset() {
	*x = MCPTool{}
	mi := &file_proto_mcp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPTool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPTool) ProtoMessage() {}

func (x *MCPTool) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPTool.ProtoReflect.Descriptor instead.
func (*MCPTool) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{10}
}

func (x *MCPTool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MCPTool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MCPTool) GetInputSchema() string {
	if x != nil {
		return x.InputSchema
	}
	return ""
}

func (x *MCPTool) GetPermissionLevel() string {
	if x != nil {
		return x.PermissionLevel
	}
	return ""
}

func (x *MCPTool) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

type CallToolRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerId         string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ToolName         string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Arguments        string                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	WorkspaceDir     string                 `protobuf:"bytes,4,opt,name=workspace_dir,json=workspaceDir,proto3" json:"workspace_dir,omitempty"`
	PermissionLevel  string                 `protobuf:"bytes,5,opt,name=permission_level,json=permissionLevel,proto3" json:"permission_level,omitempty"`
	RequiresApproval bool                   `protobuf:"varint,6,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	ApprovalId       string                 `protobuf:"bytes,7,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	ApprovalToken    string                 `protobuf:"bytes,8,opt,name=approval_token,json=approvalToken,proto3" json:"approval_token,omitempty"`
	RunId            string                 `protobuf:"bytes,9,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CallToolRequest) Reset() {
	*x = CallToolRequest{}
	mi := &file_proto_mcp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolRequest) ProtoMessage() {}

func (x *CallToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolRequest.ProtoReflect.Descriptor instead.
func (*CallToolRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{11}
}

func (x *CallToolRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CallToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *CallToolRequest) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *CallToolRequest) GetWorkspaceDir() string {
	if x != nil {
		return x.WorkspaceDir
	}
	return ""
}

func (x *CallToolRequest) GetPermissionLevel() string {
	if x != nil {
		return x.PermissionLevel
	}
	return ""
}

func (x *CallToolRequest) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

func (x *CallToolRequest) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *CallToolRequest) GetApprovalToken() string {
	if x != nil {
		return x.ApprovalToken
	}
	return ""
}

func (x *CallToolRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type CallResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerId         string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Tool             string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	Ok               bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Result           string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Error            string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode        string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	PermissionLevel  string                 `protobuf:"bytes,7,opt,name=permission_level,json=permissionLevel,proto3" json:"permission_level,omitempty"`
	RequiresApproval bool                   `protobuf:"varint,8,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CallResult) Reset() {
	*x = CallResult{}
	mi := &file_proto_mcp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResult) ProtoMessage() {}

func (x *CallResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResult.ProtoReflect.Descriptor instead.
func (*CallResult) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{12}
}

func (x *CallResult) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CallResult) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *CallResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CallResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CallResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CallResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *CallResult) GetPermissionLevel() string {
	if x != nil {
		return x.PermissionLevel
	}
	return ""
}

func (x *CallResult) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_mcp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{13}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_mcp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{14}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_mcp_proto protoreflect.FileDescriptor

const file_proto_mcp_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/mcp.proto\x12\x0enanocursor.mcp\"\x14\n" +
	"\x12ListPresetsRequest\">\n" +
	"\n" +
	"PresetList\x120\n" +
	"\apresets\x18\x01 \x03(\v2\x16.nanocursor.mcp.PresetR\apresets\"\xe7\x01\n" +
	"\x06Preset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x121\n" +
	"\x03env\x18\x06 \x03(\v2\x1f.nanocursor.mcp.Preset.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x14\n" +
	"\x12ListServersRequest\">\n" +
	"\n" +
	"ServerList\x120\n" +
	"\aservers\x18\x01 \x03(\v2\x16.nanocursor.mcp.ServerR\aservers\"\xdd\x01\n" +
	"\x06Server\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x121\n" +
	"\x03env\x18\x05 \x03(\v2\x1f.nanocursor.mcp.Server.EnvEntryR\x03env\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x02\n" +
	"\fProbeRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12#\n" +
	"\rworkspace_dir\x18\x02 \x01(\tR\fworkspaceDir\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x127\n" +
	"\x03env\x18\x05 \x03(\v2%.nanocursor.mcp.ProbeRequest.EnvEntryR\x03env\x12\x19\n" +
	"\benv_keys\x18\x06 \x03(\tR\aenvKeys\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\vProbeResult\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"/\n" +
	"\x10ListToolsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"w\n" +
	"\bToolList\x12-\n" +
	"\x05tools\x18\x01 \x03(\v2\x17.nanocursor.mcp.MCPToolR\x05tools\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xba\x01\n" +
	"\aMCPTool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\finput_schema\x18\x03 \x01(\tR\vinputSchema\x12)\n" +
	"\x10permission_level\x18\x04 \x01(\tR\x0fpermissionLevel\x12+\n" +
	"\x11requires_approval\x18\x05 \x01(\bR\x10requiresApproval\"\xc5\x02\n" +
	"\x0fCallToolRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\x12#\n" +
	"\rworkspace_dir\x18\x04 \x01(\tR\fworkspaceDir\x12)\n" +
	"\x10permission_level\x18\x05 \x01(\tR\x0fpermissionLevel\x12+\n" +
	"\x11requires_approval\x18\x06 \x01(\bR\x10requiresApproval\x12\x1f\n" +
	"\vapproval_id\x18\a \x01(\tR\n" +
	"approvalId\x12%\n" +
	"\x0eapproval_token\x18\b \x01(\tR\rapprovalToken\x12\x15\n" +
	"\x06run_id\x18\t \x01(\tR\x05runId\"\xf2\x01\n" +
	"\n" +
	"CallResult\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x12)\n" +
	"\x10permission_level\x18\a \x01(\tR\x0fpermissionLevel\x12+\n" +
	"\x11requires_approval\x18\b \x01(\bR\x10requiresApproval\"\x0f\n" +
	"\rHealthRequest\"T\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion2\xd5\x03\n" +
	"\n" +
	"MCPService\x12M\n" +
	"\vListPresets\x12\".nanocursor.mcp.ListPresetsRequest\x1a\x1a.nanocursor.mcp.PresetList\x12M\n" +
	"\vListServers\x12\".nanocursor.mcp.ListServersRequest\x1a\x1a.nanocursor.mcp.ServerList\x12H\n" +
	"\vProbeServer\x12\x1c.nanocursor.mcp.ProbeRequest\x1a\x1b.nanocursor.mcp.ProbeResult\x12M\n" +
	"\x0fListServerTools\x12 .nanocursor.mcp.ListToolsRequest\x1a\x18.nanocursor.mcp.ToolList\x12G\n" +
	"\bCallTool\x12\x1f.nanocursor.mcp.CallToolRequest\x1a\x1a.nanocursor.mcp.CallResult\x12G\n" +
	"\x06Health\x12\x1d.nanocursor.mcp.HealthRequest\x1a\x1e.nanocursor.mcp.HealthResponseB\"Z nanocursor/go-services/mcp/protob\x06proto3"

var (
	file_proto_mcp_proto_rawDescOnce sync.Once
	file_proto_mcp_proto_rawDescData []byte
)

func file_proto_mcp_proto_rawDescGZIP() []byte {
	file_proto_mcp_proto_rawDescOnce.Do(func() {
		file_proto_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mcp_proto_rawDesc), len(file_proto_mcp_proto_rawDesc)))
	})
	return file_proto_mcp_proto_rawDescData
}

var file_proto_mcp_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_mcp_proto_goTypes = []any{
	(*ListPresetsRequest)(nil), // 0: nanocursor.mcp.ListPresetsRequest
	(*PresetList)(nil),         // 1: nanocursor.mcp.PresetList
	(*Preset)(nil),             // 2: nanocursor.mcp.Preset
	(*ListServersRequest)(nil), // 3: nanocursor.mcp.ListServersRequest
	(*ServerList)(nil),         // 4: nanocursor.mcp.ServerList
	(*Server)(nil),             // 5: nanocursor.mcp.Server
	(*ProbeRequest)(nil),       // 6: nanocursor.mcp.ProbeRequest
	(*ProbeResult)(nil),        // 7: nanocursor.mcp.ProbeResult
	(*ListToolsRequest)(nil),   // 8: nanocursor.mcp.ListToolsRequest
	(*ToolList)(nil),           // 9: nanocursor.mcp.ToolList
	(*MCPTool)(nil),            // 10: nanocursor.mcp.MCPTool
	(*CallToolRequest)(nil),    // 11: nanocursor.mcp.CallToolRequest
	(*CallResult)(nil),         // 12: nanocursor.mcp.CallResult
	(*HealthRequest)(nil),      // 13: nanocursor.mcp.HealthRequest
	(*HealthResponse)(nil),     // 14: nanocursor.mcp.HealthResponse
	nil,                        // 15: nanocursor.mcp.Preset.EnvEntry
	nil,                        // 16: nanocursor.mcp.Server.EnvEntry
	nil,                        // 17: nanocursor.mcp.ProbeRequest.EnvEntry
}
var file_proto_mcp_proto_depIdxs = []int32{
	2,  // 0: nanocursor.mcp.PresetList.presets:type_name -> nanocursor.mcp.Preset
	15, // 1: nanocursor.mcp.Preset.env:type_name -> nanocursor.mcp.Preset.EnvEntry
	5,  // 2: nanocursor.mcp.ServerList.servers:type_name -> nanocursor.mcp.Server
	16, // 3: nanocursor.mcp.Server.env:type_name -> nanocursor.mcp.Server.EnvEntry
	17, // 4: nanocursor.mcp.ProbeRequest.env:type_name -> nanocursor.mcp.ProbeRequest.EnvEntry
	10, // 5: nanocursor.mcp.ToolList.tools:type_name -> nanocursor.mcp.MCPTool
	0,  // 6: nanocursor.mcp.MCPService.ListPresets:input_type -> nanocursor.mcp.ListPresetsRequest
	3,  // 7: nanocursor.mcp.MCPService.ListServers:input_type -> nanocursor.mcp.ListServersRequest
	6,  // 8: nanocursor.mcp.MCPService.ProbeServer:input_type -> nanocursor.mcp.ProbeRequest
	8,  // 9: nanocursor.mcp.MCPService.ListServerTools:input_type -> nanocursor.mcp.ListToolsRequest
	11, // 10: nanocursor.mcp.MCPService.CallTool:input_type -> nanocursor.mcp.CallToolRequest
	13, // 11: nanocursor.mcp.MCPService.Health:input_type -> nanocursor.mcp.HealthRequest
	1,  // 12: nanocursor.mcp.MCPService.ListPresets:output_type -> nanocursor.mcp.PresetList
	4,  // 13: nanocursor.mcp.MCPService.ListServers:output_type -> nanocursor.mcp.ServerList
	7,  // 14: nanocursor.mcp.MCPService.ProbeServer:output_type -> nanocursor.mcp.ProbeResult
	9,  // 15: nanocursor.mcp.MCPService.ListServerTools:output_type -> nanocursor.mcp.ToolList
	12, // 16: nanocursor.mcp.MCPService.CallTool:output_type -> nanocursor.mcp.CallResult
	14, // 17: nanocursor.mcp.MCPService.Health:output_type -> nanocursor.mcp.HealthResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_mcp_proto_init() }
func file_proto_mcp_proto_init() {
	if File_proto_mcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mcp_proto_rawDesc), len(file_proto_mcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mcp_proto_goTypes,
		DependencyIndexes: file_proto_mcp_proto_depIdxs,
		MessageInfos:      file_proto_mcp_proto_msgTypes,
	}.Build()
	File_proto_mcp_proto = out.File
	file_proto_mcp_proto_goTypes = nil
	file_proto_mcp_proto_depIdxs = nil
}
