// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/mcp.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MCPService_ListPresets_FullMethodName     = "/nanocursor.mcp.MCPService/ListPresets"
	MCPService_ListServers_FullMethodName     = "/nanocursor.mcp.MCPService/ListServers"
	MCPService_ProbeServer_FullMethodName     = "/nanocursor.mcp.MCPService/ProbeServer"
	MCPService_ListServerTools_FullMethodName = "/nanocursor.mcp.MCPService/ListServerTools"
	MCPService_CallTool_FullMethodName        = "/nanocursor.mcp.MCPService/CallTool"
	MCPService_Health_FullMethodName          = "/nanocursor.mcp.MCPService/Health"
)

// MCPServiceClient is the client API for MCPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MCPServiceClient interface {
	ListPresets(ctx context.Context, in *ListPresetsRequest, opts ...grpc.CallOption) (*PresetList, error)
	ListServers(ctx context.Context, in *ListServersRequest, opts ...grpc.CallOption) (*ServerList, error)
	ProbeServer(ctx context.Context, in *ProbeRequest, opts ...grpc.CallOption) (*ProbeResult, error)
	ListServerTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ToolList, error)
	CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallResult, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type mCPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMCPServiceClient(cc grpc.ClientConnInterface) MCPServiceClient {
	return &mCPServiceClient{cc}
}

func (c *mCPServiceClient) ListPresets(ctx context.Context, in *ListPresetsRequest, opts ...grpc.CallOption) (*PresetList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresetList)
	err := c.cc.Invoke(ctx, MCPService_ListPresets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) ListServers(ctx context.Context, in *ListServersRequest, opts ...grpc.CallOption) (*ServerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerList)
	err := c.cc.Invoke(ctx, MCPService_ListServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) ProbeServer(ctx context.Context, in *ProbeRequest, opts ...grpc.CallOption) (*ProbeResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeResult)
	err := c.cc.Invoke(ctx, MCPService_ProbeServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) ListServerTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ToolList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolList)
	err := c.cc.Invoke(ctx, MCPService_ListServerTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResult)
	err := c.cc.Invoke(ctx, MCPService_CallTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, MCPService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MCPServiceServer is the server API for MCPService service.
// All implementations must embed UnimplementedMCPServiceServer
// for forward compatibility.
type MCPServiceServer interface {
	ListPresets(context.Context, *ListPresetsRequest) (*PresetList, error)
	ListServers(context.Context, *ListServersRequest) (*ServerList, error)
	ProbeServer(context.Context, *ProbeRequest) (*ProbeResult, error)
	ListServerTools(context.Context, *ListToolsRequest) (*ToolList, error)
	CallTool(context.Context, *CallToolRequest) (*CallResult, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedMCPServiceServer()
}

// UnimplementedMCPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMCPServiceServer struct{}

func (UnimplementedMCPServiceServer) ListPresets(context.Context, *ListPresetsRequest) (*PresetList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPresets not implemented")
}
func (UnimplementedMCPServiceServer) ListServers(context.Context, *ListServersRequest) (*ServerList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServers not implemented")
}
func (UnimplementedMCPServiceServer) ProbeServer(context.Context, *ProbeRequest) (*ProbeResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbeServer not implemented")
}
func (UnimplementedMCPServiceServer) ListServerTools(context.Context, *ListToolsRequest) (*ToolList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServerTools not implemented")
}
func (UnimplementedMCPServiceServer) CallTool(context.Context, *CallToolRequest) (*CallResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CallTool not implemented")
}
func (UnimplementedMCPServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedMCPServiceServer) mustEmbedUnimplementedMCPServiceServer() {}
func (UnimplementedMCPServiceServer) testEmbeddedByValue()                    {}

// UnsafeMCPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MCPServiceServer will
// result in compilation errors.
type UnsafeMCPServiceServer interface {
	mustEmbedUnimplementedMCPServiceServer()
}

func RegisterMCPServiceServer(s grpc.ServiceRegistrar, srv MCPServiceServer) {
	// If the following call panics, it indicates UnimplementedMCPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MCPService_ServiceDesc, srv)
}

func _MCPService_ListPresets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPresetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).ListPresets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_ListPresets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).ListPresets(ctx, req.(*ListPresetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_ListServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).ListServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_ListServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).ListServers(ctx, req.(*ListServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_ProbeServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).ProbeServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_ProbeServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).ProbeServer(ctx, req.(*ProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_ListServerTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).ListServerTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_ListServerTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).ListServerTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_CallTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).CallTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_CallTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).CallTool(ctx, req.(*CallToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MCPService_ServiceDesc is the grpc.ServiceDesc for MCPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MCPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanocursor.mcp.MCPService",
	HandlerType: (*MCPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPresets",
			Handler:    _MCPService_ListPresets_Handler,
		},
		{
			MethodName: "ListServers",
			Handler:    _MCPService_ListServers_Handler,
		},
		{
			MethodName: "ProbeServer",
			Handler:    _MCPService_ProbeServer_Handler,
		},
		{
			MethodName: "ListServerTools",
			Handler:    _MCPService_ListServerTools_Handler,
		},
		{
			MethodName: "CallTool",
			Handler:    _MCPService_CallTool_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _MCPService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mcp.proto",
}
