package mcp

func Presets() []Preset {
	return []Preset{
		{
			ID:             "filesystem",
			ServerID:       "mcp.filesystem",
			Name:           "Local Filesystem",
			Description:    "Expose the current workspace as a scoped MCP filesystem context.",
			Command:        "npx",
			Args:           []string{"-y", "@modelcontextprotocol/server-filesystem", "{{workspace_dir}}"},
			EnvKeys:        []string{},
			EnabledDefault: true,
			Requires:       []string{"Node.js", "npx"},
			SecurityNote:   "Only the active nanoCursor workspace should be exposed.",
		},
		{
			ID:             "docs",
			ServerID:       "mcp.docs",
			Name:           "Docs Knowledge Base",
			Description:    "Prefer docs/ as a scoped documentation knowledge base.",
			Command:        "npx",
			Args:           []string{"-y", "@modelcontextprotocol/server-filesystem", "{{docs_or_workspace}}"},
			EnvKeys:        []string{},
			EnabledDefault: true,
			Requires:       []string{"Node.js", "npx"},
			SecurityNote:   "Use for project docs and design notes, not secrets.",
		},
		{
			ID:             "memory",
			ServerID:       "mcp.memory",
			Name:           "Memory Graph",
			Description:    "Lightweight graph memory for project facts and preferences.",
			Command:        "npx",
			Args:           []string{"-y", "@modelcontextprotocol/server-memory"},
			EnvKeys:        []string{},
			EnabledDefault: true,
			Requires:       []string{"Node.js", "npx"},
			SecurityNote:   "Do not store secrets, tokens, or private data.",
		},
		{
			ID:             "sequential-thinking",
			ServerID:       "mcp.sequential-thinking",
			Name:           "Sequential Thinking",
			Description:    "Structured reasoning support for complex plans and debugging.",
			Command:        "npx",
			Args:           []string{"-y", "@modelcontextprotocol/server-sequential-thinking"},
			EnvKeys:        []string{},
			EnabledDefault: true,
			Requires:       []string{"Node.js", "npx"},
			SecurityNote:   "Reasoning-only preset, no direct workspace write access.",
		},
		{
			ID:             "github",
			ServerID:       "mcp.github",
			Name:           "GitHub",
			Description:    "Access GitHub issues, PRs, review context, and CI state.",
			Command:        "docker",
			Args:           []string{"run", "-i", "--rm", "-e", "GITHUB_PERSONAL_ACCESS_TOKEN", "ghcr.io/github/github-mcp-server"},
			EnvKeys:        []string{"GITHUB_PERSONAL_ACCESS_TOKEN"},
			EnabledDefault: false,
			Requires:       []string{"Docker", "GITHUB_PERSONAL_ACCESS_TOKEN"},
			SecurityNote:   "Use a least-privilege token and keep this disabled by default.",
		},
	}
}
